package hypervisor

import (
	"bytes"
	"fmt"
	"net"
	"os"
	"os/exec"
	"regexp"
	"strings"
	"testing"

	"github.com/google/go-cmp/cmp"
	zconfig "github.com/lf-edge/eve-api/go/config"
	zcommon "github.com/lf-edge/eve-api/go/evecommon"
	"github.com/lf-edge/eve/pkg/pillar/types"
	. "github.com/onsi/gomega"
	uuid "github.com/satori/go.uuid"
)

const (
	// DefaultUUID is the default UUID for the domain
	DefaultUUID = "e4f1c2a7-9b3d-4e5f-8a6b-2c7d9e0f1a2b"
	// DefaultDomainName is the default domain name
	DefaultDomainName = DefaultUUID + ".0.0"
)

var kvmIntel, kvmArm KvmContext
var swtpmCtrlSock = ""

// these ones are very much handcrafted just for the tests
func init() {
	kvmIntel = KvmContext{
		devicemodel: "pc-q35-3.1",
		dmExec:      "",
		dmArgs:      []string{},
	}
	kvmArm = KvmContext{
		devicemodel: "virt",
		dmExec:      "",
		dmArgs:      []string{},
	}
}

// setStaticVsockCid is a helper function to set the guest-cid to a static value
// in the resulting config file otherwise the test will fail because the guest-cid
// is incremented every time config file is generated.
func setStaticVsockCid(input []byte) []byte {
	re := regexp.MustCompile(`guest-cid\s*=\s*"\d+"`)
	out := re.ReplaceAllString(string(input), `guest-cid = "3"`)
	return []byte(out)
}

func TestCreateDomConfigOnlyCom1(t *testing.T) {
	id, err := uuid.NewV4()
	if err != nil {
		t.Errorf("NewV4 failed: %v", err)
	}
	config := types.DomainConfig{
		UUIDandVersion: types.UUIDandVersion{UUID: id, Version: "1.0"},
		VmConfig: types.VmConfig{
			Kernel:     "/boot/kernel",
			Ramdisk:    "/boot/ramdisk",
			ExtraArgs:  "init=/bin/sh",
			Memory:     1024 * 1024 * 10,
			VCpus:      2,
			VncDisplay: 5,
			VncPasswd:  "rosebud",
		},
		GPUConfig: "legacy",
		VifList: []types.VifConfig{
			{Bridge: "bn0", Mac: net.HardwareAddr{0x6a, 0x00, 0x03, 0x61, 0xa6, 0x90}, Vif: "nbu1x1"},
			{Bridge: "bn0", Mac: net.HardwareAddr{0x6a, 0x00, 0x03, 0x61, 0xa6, 0x91}, Vif: "nbu1x2"},
		},
		IoAdapterList: []types.IoAdapter{
			{Type: types.IoCom, Name: "COM1"},
		},
	}
	disks := []types.DiskStatus{
		{Format: zconfig.Format_QCOW2, FileLocation: "/foo/bar.qcow2", Devtype: "hdd"},
		{Format: zconfig.Format_CONTAINER, FileLocation: "/foo/container", Devtype: "9P"},
		{Format: zconfig.Format_RAW, FileLocation: "/foo/bar.raw", Devtype: "hdd"},
		{Format: zconfig.Format_RAW, FileLocation: "/foo/cd.iso", Devtype: "cdrom"},
		{Format: zconfig.Format_CONTAINER, FileLocation: "/foo/volume", Devtype: ""},
	}
	aa := types.AssignableAdapters{
		Initialized: true,
		IoBundleList: []types.IoBundle{
			{
				Type:            types.IoCom,
				AssignmentGroup: "COM1",
				Phylabel:        "COM1",
				Ifname:          "COM1",
				Serial:          "/dev/ttyS0",
				UsedByUUID:      config.UUIDandVersion.UUID,
			},
		},
	}
	conf, err := os.CreateTemp("/tmp", "config")
	if err != nil {
		t.Errorf("Can't create config file for a domain %v", err)
	} else {
		defer os.Remove(conf.Name())
	}

	t.Run("amd64", func(t *testing.T) {
		conf.Seek(0, 0)
		if err := kvmIntel.CreateDomConfig(DefaultDomainName, config, types.DomainStatus{},
			disks, &aa, nil, swtpmCtrlSock, conf); err != nil {
			t.Errorf("CreateDomConfig failed %v", err)
		}
		defer os.Truncate(conf.Name(), 0)

		result, err := os.ReadFile(conf.Name())
		if err != nil {
			t.Errorf("reading conf file failed %v", err)
		}

		// this is the only way to get the expected output (◔_◔)
		result = setStaticVsockCid(result)
		expected := fmt.Sprintf(`# This file is automatically generated by domainmgr
[msg]
  timestamp = "on"

[machine]
  type = "pc-q35-3.1"
  dump-guest-core = "off"
  accel = "kvm"
  vmport = "off"
  kernel-irqchip = "on"
  kernel = "/boot/kernel"
  initrd = "/boot/ramdisk"
  append = "init=/bin/sh"

[global]
  driver = "kvm-pit"
  property = "lost_tick_policy"
  value = "delay"

[global]
  driver = "ICH9-LPC"
  property = "disable_s3"
  value = "1"

[global]
  driver = "ICH9-LPC"
  property = "disable_s4"
  value = "1"

[rtc]
  base = "localtime"
  driftfix = "slew"

[device]
  driver = "intel-iommu"
  caching-mode = "on"

[overcommit]
  mem-lock = "off"

[chardev "charmonitor"]
  backend = "socket"
  path = "/run/hypervisor/kvm/%s/qmp"
  server = "on"
  wait = "off"

[mon "monitor"]
  chardev = "charmonitor"
  mode = "control"

[chardev "charlistener"]
  backend = "socket"
  path = "/run/hypervisor/kvm/%s/listener.qmp"
  server = "on"
  wait = "off"

[mon "listener"]
  chardev = "charlistener"
  mode = "control"

[memory]
  size = "10240"

[smp-opts]
  cpus = "2"
  sockets = "1"
  cores = "2"
  threads = "1"

[device]
  driver = "virtio-serial"
  addr = "3"

[chardev "charserial0"]
  backend = "socket"
  mux = "on"
  path = "/run/hypervisor/kvm/%s/cons"
  server = "on"
  wait = "off"
  logfile = "/dev/fd/1"
  logappend = "on"

[device]
  driver = "virtconsole"
  chardev = "charserial0"
  name = "org.lfedge.eve.console.0"



[device "pci.2"]
  driver = "pcie-root-port"
  port = "12"
  chassis = "2"
  bus = "pcie.0"
  addr = "0x2"

[device "usb"]
  driver = "qemu-xhci"
  p2 = "15"
  p3 = "15"
  bus = "pci.2"
  addr = "0x0"

[device "input0"]
  driver = "usb-tablet"
  bus = "usb.0"
  port = "1"


[device "pci.4"]
  driver = "pcie-root-port"
  port = "14"
  chassis = "4"
  bus = "pcie.0"
  addr = "0x4"

[drive "drive-virtio-disk0"]
  file = "/foo/bar.qcow2"
  format = "qcow2"
  aio = "io_uring"
  cache = "writeback"
  if = "none"

[device "virtio-disk0"]
  driver = "virtio-blk-pci"
  scsi = "off"
  bus = "pci.4"
  addr = "0x0"
  drive = "drive-virtio-disk0"


[fsdev "fsdev1"]
  fsdriver = "local"
  security_model = "none"
  multidevs = "remap"
  path = "/foo/container"

[device "fs1"]
  driver = "virtio-9p-pci"
  fsdev = "fsdev1"
  mount_tag = "share_dir"
  addr = "0x5"


[device "pci.6"]
  driver = "pcie-root-port"
  port = "16"
  chassis = "6"
  bus = "pcie.0"
  addr = "0x6"

[drive "drive-virtio-disk2"]
  file = "/foo/bar.raw"
  format = "raw"
  aio = "io_uring"
  cache = "writeback"
  if = "none"

[device "virtio-disk2"]
  driver = "virtio-blk-pci"
  scsi = "off"
  bus = "pci.6"
  addr = "0x0"
  drive = "drive-virtio-disk2"


[drive "drive-sata0-3"]
  file = "/foo/cd.iso"
  format = "raw"
  if = "none"
  media = "cdrom"
  readonly = "on"

[device "sata0-0"]
  drive = "drive-sata0-3"
  driver = "ide-cd"
  bus = "ide.0"

[device "pci.7"]
  driver = "pcie-root-port"
  port = "17"
  chassis = "7"
  bus = "pcie.0"
  multifunction = "on"
  addr = "0x7"

[netdev "hostnet0"]
  type = "tap"
  ifname = "nbu1x1"
  br = "bn0"
  script = "/etc/xen/scripts/qemu-ifup"
  downscript = "no"
  vhost = "on"

[device "net0"]
  driver = "virtio-net-pci"
  netdev = "hostnet0"
  mac = "6a:00:03:61:a6:90"
  bus = "pci.7"
  addr = "0x0"

[device "pci.8"]
  driver = "pcie-root-port"
  port = "18"
  chassis = "8"
  bus = "pcie.0"
  multifunction = "on"
  addr = "0x8"

[netdev "hostnet1"]
  type = "tap"
  ifname = "nbu1x2"
  br = "bn0"
  script = "/etc/xen/scripts/qemu-ifup"
  downscript = "no"
  vhost = "on"

[device "net1"]
  driver = "virtio-net-pci"
  netdev = "hostnet1"
  mac = "6a:00:03:61:a6:91"
  bus = "pci.8"
  addr = "0x0"

[chardev "charserial-usr0"]
  backend = "serial"
  path = "/dev/ttyS0"

[device "serial-usr0"]
  driver = "isa-serial"
  chardev = "charserial-usr0"

[device "eve-vsock0"]
  driver = "vhost-vsock-pci"
  disable-legacy = "on"
  guest-cid = "3"
`, DefaultDomainName, DefaultDomainName, DefaultDomainName)
		if string(result) != expected {
			t.Errorf("got an unexpected resulting config %s", string(result))
		}
	})

	config.VirtualizationMode = types.FML
	config.BootLoader = "/usr/lib/xen/boot/OVMF_CODE.fd"
	t.Run("amd64-fml", func(t *testing.T) {
		conf.Seek(0, 0)
		if err := kvmIntel.CreateDomConfig(DefaultDomainName, config, types.DomainStatus{},
			disks, &aa, nil, swtpmCtrlSock, conf); err != nil {
			t.Errorf("CreateDomConfig failed %v", err)
		}
		defer os.Truncate(conf.Name(), 0)

		result, err := os.ReadFile(conf.Name())
		if err != nil {
			t.Errorf("reading conf file failed %v", err)
		}

		result = setStaticVsockCid(result)
		expected := fmt.Sprintf(`# This file is automatically generated by domainmgr
[msg]
  timestamp = "on"

[machine]
  type = "pc-q35-3.1"
  dump-guest-core = "off"
  accel = "kvm"
  vmport = "off"
  kernel-irqchip = "on"
  kernel = "/boot/kernel"
  initrd = "/boot/ramdisk"
  append = "init=/bin/sh"

[global]
  driver = "kvm-pit"
  property = "lost_tick_policy"
  value = "delay"

[global]
  driver = "ICH9-LPC"
  property = "disable_s3"
  value = "1"

[global]
  driver = "ICH9-LPC"
  property = "disable_s4"
  value = "1"

[rtc]
  base = "localtime"
  driftfix = "slew"

[device]
  driver = "intel-iommu"
  caching-mode = "on"

[drive "drive-ovmf-code"]
  if = "pflash"
  format = "raw"
  readonly = "on"
  unit = "0"
  file = "/usr/lib/xen/boot/OVMF_CODE.fd"

[drive "drive-ovmf-vars"]
  if = "pflash"
  format = "raw"
  unit = "1"
  file = "/persist/vault/ovmf/%s_OVMF_VARS.fd"

[overcommit]
  mem-lock = "off"

[chardev "charmonitor"]
  backend = "socket"
  path = "/run/hypervisor/kvm/%s/qmp"
  server = "on"
  wait = "off"

[mon "monitor"]
  chardev = "charmonitor"
  mode = "control"

[chardev "charlistener"]
  backend = "socket"
  path = "/run/hypervisor/kvm/%s/listener.qmp"
  server = "on"
  wait = "off"

[mon "listener"]
  chardev = "charlistener"
  mode = "control"

[memory]
  size = "10240"

[smp-opts]
  cpus = "2"
  sockets = "1"
  cores = "2"
  threads = "1"

[device]
  driver = "virtio-serial"
  addr = "3"

[chardev "charserial0"]
  backend = "socket"
  mux = "on"
  path = "/run/hypervisor/kvm/%s/cons"
  server = "on"
  wait = "off"
  logfile = "/dev/fd/1"
  logappend = "on"

[device]
  driver = "virtconsole"
  chardev = "charserial0"
  name = "org.lfedge.eve.console.0"



[device "pci.2"]
  driver = "pcie-root-port"
  port = "12"
  chassis = "2"
  bus = "pcie.0"
  addr = "0x2"

[device "usb"]
  driver = "qemu-xhci"
  p2 = "15"
  p3 = "15"
  bus = "pci.2"
  addr = "0x0"

[device "input0"]
  driver = "usb-tablet"
  bus = "usb.0"
  port = "1"


[device "pci.4"]
  driver = "pcie-root-port"
  port = "14"
  chassis = "4"
  bus = "pcie.0"
  addr = "0x4"

[drive "drive-virtio-disk0"]
  file = "/foo/bar.qcow2"
  format = "qcow2"
  aio = "io_uring"
  cache = "writeback"
  if = "none"

[device "virtio-disk0"]
  driver = "virtio-blk-pci"
  scsi = "off"
  bus = "pci.4"
  addr = "0x0"
  drive = "drive-virtio-disk0"


[fsdev "fsdev1"]
  fsdriver = "local"
  security_model = "none"
  multidevs = "remap"
  path = "/foo/container"

[device "fs1"]
  driver = "virtio-9p-pci"
  fsdev = "fsdev1"
  mount_tag = "share_dir"
  addr = "0x5"


[device "pci.6"]
  driver = "pcie-root-port"
  port = "16"
  chassis = "6"
  bus = "pcie.0"
  addr = "0x6"

[drive "drive-virtio-disk2"]
  file = "/foo/bar.raw"
  format = "raw"
  aio = "io_uring"
  cache = "writeback"
  if = "none"

[device "virtio-disk2"]
  driver = "virtio-blk-pci"
  scsi = "off"
  bus = "pci.6"
  addr = "0x0"
  drive = "drive-virtio-disk2"


[drive "drive-sata0-3"]
  file = "/foo/cd.iso"
  format = "raw"
  if = "none"
  media = "cdrom"
  readonly = "on"

[device "sata0-0"]
  drive = "drive-sata0-3"
  driver = "ide-cd"
  bus = "ide.0"

[device "pci.7"]
  driver = "pcie-root-port"
  port = "17"
  chassis = "7"
  bus = "pcie.0"
  multifunction = "on"
  addr = "0x7"

[netdev "hostnet0"]
  type = "tap"
  ifname = "nbu1x1"
  br = "bn0"
  script = "/etc/xen/scripts/qemu-ifup"
  downscript = "no"
  vhost = "on"

[device "net0"]
  driver = "virtio-net-pci"
  netdev = "hostnet0"
  mac = "6a:00:03:61:a6:90"
  bus = "pci.7"
  addr = "0x0"

[device "pci.8"]
  driver = "pcie-root-port"
  port = "18"
  chassis = "8"
  bus = "pcie.0"
  multifunction = "on"
  addr = "0x8"

[netdev "hostnet1"]
  type = "tap"
  ifname = "nbu1x2"
  br = "bn0"
  script = "/etc/xen/scripts/qemu-ifup"
  downscript = "no"
  vhost = "on"

[device "net1"]
  driver = "virtio-net-pci"
  netdev = "hostnet1"
  mac = "6a:00:03:61:a6:91"
  bus = "pci.8"
  addr = "0x0"

[chardev "charserial-usr0"]
  backend = "serial"
  path = "/dev/ttyS0"

[device "serial-usr0"]
  driver = "isa-serial"
  chardev = "charserial-usr0"

[device "eve-vsock0"]
  driver = "vhost-vsock-pci"
  disable-legacy = "on"
  guest-cid = "3"
`, DefaultUUID, DefaultDomainName, DefaultDomainName, DefaultDomainName)
		if string(result) != expected {
			t.Errorf("got an unexpected resulting config %s", string(result))
		}
	})

	config.VirtualizationMode = types.HVM
	config.BootLoader = "/usr/lib/xen/boot/ovmf.bin"
	t.Run("arm64", func(t *testing.T) {
		conf.Seek(0, 0)
		if err := kvmArm.CreateDomConfig(DefaultDomainName, config, types.DomainStatus{},
			disks, &aa, nil, swtpmCtrlSock, conf); err != nil {
			t.Errorf("CreateDomConfig failed %v", err)
		}
		defer os.Truncate(conf.Name(), 0)

		result, err := os.ReadFile(conf.Name())
		if err != nil {
			t.Errorf("reading conf file failed %v", err)
		}

		result = setStaticVsockCid(result)
		expected := fmt.Sprintf(`# This file is automatically generated by domainmgr
[msg]
  timestamp = "on"

[machine]
  type = "virt"
  dump-guest-core = "off"
  accel = "kvm:tcg"
  gic-version = "host"
  firmware = "/usr/lib/xen/boot/ovmf.bin"
  kernel = "/boot/kernel"
  initrd = "/boot/ramdisk"
  append = "init=/bin/sh"


[overcommit]
  mem-lock = "off"

[chardev "charmonitor"]
  backend = "socket"
  path = "/run/hypervisor/kvm/%s/qmp"
  server = "on"
  wait = "off"

[mon "monitor"]
  chardev = "charmonitor"
  mode = "control"

[chardev "charlistener"]
  backend = "socket"
  path = "/run/hypervisor/kvm/%s/listener.qmp"
  server = "on"
  wait = "off"

[mon "listener"]
  chardev = "charlistener"
  mode = "control"

[memory]
  size = "10240"

[smp-opts]
  cpus = "2"
  sockets = "1"
  cores = "2"
  threads = "1"

[device]
  driver = "virtio-serial"
  addr = "3"

[chardev "charserial0"]
  backend = "socket"
  mux = "on"
  path = "/run/hypervisor/kvm/%s/cons"
  server = "on"
  wait = "off"
  logfile = "/dev/fd/1"
  logappend = "on"

[device]
  driver = "virtconsole"
  chardev = "charserial0"
  name = "org.lfedge.eve.console.0"



[device "pci.2"]
  driver = "pcie-root-port"
  port = "12"
  chassis = "2"
  bus = "pcie.0"
  addr = "0x2"

[device "usb"]
  driver = "qemu-xhci"
  p2 = "15"
  p3 = "15"
  bus = "pci.2"
  addr = "0x0"

[device "input0"]
  driver = "usb-kbd"
  bus = "usb.0"
  port = "1"

[device "input1"]
  driver = "usb-mouse"
  bus = "usb.0"
  port = "2"


[device "pci.4"]
  driver = "pcie-root-port"
  port = "14"
  chassis = "4"
  bus = "pcie.0"
  addr = "0x4"

[drive "drive-virtio-disk0"]
  file = "/foo/bar.qcow2"
  format = "qcow2"
  aio = "io_uring"
  cache = "writeback"
  if = "none"

[device "virtio-disk0"]
  driver = "virtio-blk-pci"
  scsi = "off"
  bus = "pci.4"
  addr = "0x0"
  drive = "drive-virtio-disk0"


[fsdev "fsdev1"]
  fsdriver = "local"
  security_model = "none"
  multidevs = "remap"
  path = "/foo/container"

[device "fs1"]
  driver = "virtio-9p-pci"
  fsdev = "fsdev1"
  mount_tag = "share_dir"
  addr = "0x5"


[device "pci.6"]
  driver = "pcie-root-port"
  port = "16"
  chassis = "6"
  bus = "pcie.0"
  addr = "0x6"

[drive "drive-virtio-disk2"]
  file = "/foo/bar.raw"
  format = "raw"
  aio = "io_uring"
  cache = "writeback"
  if = "none"

[device "virtio-disk2"]
  driver = "virtio-blk-pci"
  scsi = "off"
  bus = "pci.6"
  addr = "0x0"
  drive = "drive-virtio-disk2"


[drive "drive-sata0-3"]
  file = "/foo/cd.iso"
  format = "raw"
  if = "none"
  media = "cdrom"
  readonly = "on"

[device "sata0-0"]
  drive = "drive-sata0-3"
  driver = "usb-storage"


[device "pci.7"]
  driver = "pcie-root-port"
  port = "17"
  chassis = "7"
  bus = "pcie.0"
  multifunction = "on"
  addr = "0x7"

[netdev "hostnet0"]
  type = "tap"
  ifname = "nbu1x1"
  br = "bn0"
  script = "/etc/xen/scripts/qemu-ifup"
  downscript = "no"
  vhost = "on"

[device "net0"]
  driver = "virtio-net-pci"
  netdev = "hostnet0"
  mac = "6a:00:03:61:a6:90"
  bus = "pci.7"
  addr = "0x0"

[device "pci.8"]
  driver = "pcie-root-port"
  port = "18"
  chassis = "8"
  bus = "pcie.0"
  multifunction = "on"
  addr = "0x8"

[netdev "hostnet1"]
  type = "tap"
  ifname = "nbu1x2"
  br = "bn0"
  script = "/etc/xen/scripts/qemu-ifup"
  downscript = "no"
  vhost = "on"

[device "net1"]
  driver = "virtio-net-pci"
  netdev = "hostnet1"
  mac = "6a:00:03:61:a6:91"
  bus = "pci.8"
  addr = "0x0"

[chardev "charserial-usr0"]
  backend = "serial"
  path = "/dev/ttyS0"

[device "serial-usr0"]
  driver = "pci-serial"
  chardev = "charserial-usr0"

[object "rng0"]
  qom-type = "rng-random"
  filename = "/dev/urandom"

[device "virtio-rng0"]
  driver = "virtio-rng-pci"
  rng = "rng0"
  max-bytes = "4096"
  period = "1000"

[device "eve-vsock0"]
  driver = "vhost-vsock-pci"
  disable-legacy = "on"
  guest-cid = "3"
`, DefaultDomainName, DefaultDomainName, DefaultDomainName)
		if string(result) != expected {
			t.Errorf("got an unexpected resulting config %s", string(result))
		}
	})
}

func TestCreateDomConfigAmd64(t *testing.T) {
	t.Parallel()

	conf, err := os.CreateTemp("/tmp", "config")
	if err != nil {
		t.Errorf("Can't create config file for a domain %v", err)
	}
	defer os.Remove(conf.Name())

	diskConfigs, diskStatuses := qemuDisks()
	config, aa := domainConfigAndAssignableAdapters(diskConfigs)
	if err := kvmIntel.CreateDomConfig(DefaultDomainName, config, types.DomainStatus{},
		diskStatuses, &aa, nil, swtpmCtrlSock, conf); err != nil {
		t.Errorf("CreateDomConfig failed %v", err)
	}
	defer os.Truncate(conf.Name(), 0)

	result, err := os.ReadFile(conf.Name())
	if err != nil {
		t.Errorf("reading conf file failed %v", err)
	}

	result = setStaticVsockCid(result)
	if string(result) != domConfigAmd64() {
		t.Errorf("got an unexpected resulting config %s", string(result))
	}
}

func TestCreateDomConfigAmd64Legacy(t *testing.T) {
	t.Parallel()

	conf, err := os.CreateTemp("/tmp", "config")
	if err != nil {
		t.Errorf("Can't create config file for a domain %v", err)
	}
	defer os.Remove(conf.Name())
	diskCondigsLegacy, diskStatusesLegacy := qemuDisksLegacy()
	config, aa := domainConfigAndAssignableAdapters(diskCondigsLegacy)
	config.VirtualizationMode = types.LEGACY
	if err := kvmIntel.CreateDomConfig(DefaultDomainName, config, types.DomainStatus{},
		diskStatusesLegacy, &aa, nil, swtpmCtrlSock, conf); err != nil {
		t.Errorf("CreateDomConfig failed %v", err)
	}
	defer os.Truncate(conf.Name(), 0)

	result, err := os.ReadFile(conf.Name())
	if err != nil {
		t.Errorf("reading conf file failed %v", err)
	}

	result = setStaticVsockCid(result)
	if string(result) != domConfigAmd64Legacy() {
		t.Errorf("got an unexpected resulting config %s", string(result))
	}
}
func TestCreateDomConfigAmd64Fml(t *testing.T) {
	t.Parallel()

	conf, err := os.CreateTemp("/tmp", "config")
	if err != nil {
		t.Errorf("Can't create config file for a domain %v", err)
	}
	defer os.Remove(conf.Name())
	diskConfigs, diskStatuses := qemuDisks()
	config, aa := domainConfigAndAssignableAdapters(diskConfigs)
	config.VirtualizationMode = types.FML
	config.BootLoader = "/usr/lib/xen/boot/OVMF_CODE.fd"
	addNonExistingAdapter(&config, &aa)
	if err := kvmIntel.CreateDomConfig(DefaultDomainName, config, types.DomainStatus{},
		diskStatuses, &aa, nil, swtpmCtrlSock, conf); err != nil {
		t.Errorf("CreateDomConfig failed %v", err)
	}
	aa.IoBundleList = aa.IoBundleList[:len(aa.IoBundleList)-1]
	config.IoAdapterList = config.IoAdapterList[:len(config.IoAdapterList)-1]
	defer os.Truncate(conf.Name(), 0)

	result, err := os.ReadFile(conf.Name())
	if err != nil {
		t.Errorf("reading conf file failed %v", err)
	}

	result = setStaticVsockCid(result)
	if string(result) != domConfigAmd64FML() {
		t.Errorf("got an unexpected resulting config %s", cmp.Diff(string(result), domConfigAmd64FML()))
	}
}

func TestCreateDomConfigAmd64FmlWithBootOrder(t *testing.T) {
	t.Parallel()

	conf, err := os.CreateTemp("/tmp", "config")
	if err != nil {
		t.Errorf("Can't create config file for a domain %v", err)
	}
	defer os.Remove(conf.Name())

	diskConfigs, diskStatuses := qemuDisks()
	config, aa := domainConfigAndAssignableAdapters(diskConfigs)
	config.VirtualizationMode = types.FML
	config.BootLoader = "/usr/lib/xen/boot/OVMF_CODE.fd"
	config.BootOrder = zcommon.BootOrder_BOOT_ORDER_USB // Test USB boot order prioritization

	if err := kvmIntel.CreateDomConfig(DefaultDomainName, config, types.DomainStatus{},
		diskStatuses, &aa, nil, swtpmCtrlSock, conf); err != nil {
		t.Errorf("CreateDomConfig failed %v", err)
	}
	defer os.Truncate(conf.Name(), 0)

	result, err := os.ReadFile(conf.Name())
	if err != nil {
		t.Errorf("reading conf file failed %v", err)
	}

	// Verify that fw_cfg boot order section is present in the config
	if !bytes.Contains(result, []byte(`[fw_cfg]`)) {
		t.Error("expected [fw_cfg] section for boot order, but not found")
	}
	if !bytes.Contains(result, []byte(`name = "opt/eve.bootorder"`)) {
		t.Error("expected opt/eve.bootorder fw_cfg name, but not found")
	}
	if !bytes.Contains(result, []byte(`string = "usb"`)) {
		t.Error("expected boot order value 'usb', but not found")
	}
}

func TestCreateDomConfigAmd64FmlWithNoUsbBootOrder(t *testing.T) {
	t.Parallel()

	conf, err := os.CreateTemp("/tmp", "config")
	if err != nil {
		t.Errorf("Can't create config file for a domain %v", err)
	}
	defer os.Remove(conf.Name())

	diskConfigs, diskStatuses := qemuDisks()
	config, aa := domainConfigAndAssignableAdapters(diskConfigs)
	config.VirtualizationMode = types.FML
	config.BootLoader = "/usr/lib/xen/boot/OVMF_CODE.fd"
	config.BootOrder = zcommon.BootOrder_BOOT_ORDER_NOUSB // Test USB boot order deprioritization

	if err := kvmIntel.CreateDomConfig(DefaultDomainName, config, types.DomainStatus{},
		diskStatuses, &aa, nil, swtpmCtrlSock, conf); err != nil {
		t.Errorf("CreateDomConfig failed %v", err)
	}
	defer os.Truncate(conf.Name(), 0)

	result, err := os.ReadFile(conf.Name())
	if err != nil {
		t.Errorf("reading conf file failed %v", err)
	}

	// Verify that fw_cfg boot order section is present with nousb value
	if !bytes.Contains(result, []byte(`[fw_cfg]`)) {
		t.Error("expected [fw_cfg] section for boot order, but not found")
	}
	if !bytes.Contains(result, []byte(`string = "nousb"`)) {
		t.Error("expected boot order value 'nousb', but not found")
	}
}

func TestCreateDomConfigAmd64FmlWithoutBootOrder(t *testing.T) {
	t.Parallel()

	conf, err := os.CreateTemp("/tmp", "config")
	if err != nil {
		t.Errorf("Can't create config file for a domain %v", err)
	}
	defer os.Remove(conf.Name())

	diskConfigs, diskStatuses := qemuDisks()
	config, aa := domainConfigAndAssignableAdapters(diskConfigs)
	config.VirtualizationMode = types.FML
	config.BootLoader = "/usr/lib/xen/boot/OVMF_CODE.fd"
	// config.BootOrder is empty (default) - no boot order modification

	if err := kvmIntel.CreateDomConfig(DefaultDomainName, config, types.DomainStatus{},
		diskStatuses, &aa, nil, swtpmCtrlSock, conf); err != nil {
		t.Errorf("CreateDomConfig failed %v", err)
	}
	defer os.Truncate(conf.Name(), 0)

	result, err := os.ReadFile(conf.Name())
	if err != nil {
		t.Errorf("reading conf file failed %v", err)
	}

	// Verify that fw_cfg boot order section is NOT present when boot order is empty
	if bytes.Contains(result, []byte(`name = "opt/eve.bootorder"`)) {
		t.Error("unexpected opt/eve.bootorder fw_cfg - should not be present when boot order is empty")
	}
}

func TestCreateDomConfigArm64BootOrderIgnored(t *testing.T) {
	t.Parallel()

	conf, err := os.CreateTemp("/tmp", "config")
	if err != nil {
		t.Errorf("Can't create config file for a domain %v", err)
	}
	defer os.Remove(conf.Name())

	diskConfigs, diskStatuses := qemuDisks()
	config, aa := domainConfigAndAssignableAdapters(diskConfigs)
	config.VirtualizationMode = types.FML
	config.BootLoader = "/usr/lib/xen/boot/OVMF_CODE.fd"
	config.BootOrder = zcommon.BootOrder_BOOT_ORDER_USB // Set boot order

	// Use ARM context (virt machine) - boot order should be ignored
	if err := kvmArm.CreateDomConfig(DefaultDomainName, config, types.DomainStatus{},
		diskStatuses, &aa, nil, swtpmCtrlSock, conf); err != nil {
		t.Errorf("CreateDomConfig failed %v", err)
	}
	defer os.Truncate(conf.Name(), 0)

	result, err := os.ReadFile(conf.Name())
	if err != nil {
		t.Errorf("reading conf file failed %v", err)
	}

	// ARM (virt machine) uses an unpatched OVMF without EveBootOrderLib, so fw_cfg boot order should NOT be present
	if bytes.Contains(result, []byte(`name = "opt/eve.bootorder"`)) {
		t.Error("unexpected opt/eve.bootorder fw_cfg on ARM - EveBootOrderLib is not available on virt machine")
	}
}

func TestCreateDomConfigArm64(t *testing.T) {
	t.Parallel()

	conf, err := os.CreateTemp("/tmp", "config")
	if err != nil {
		t.Errorf("Can't create config file for a domain %v", err)
	}
	defer os.Remove(conf.Name())

	diskConfigs, diskStatuses := qemuDisks()
	config, aa := domainConfigAndAssignableAdapters(diskConfigs)
	config.VirtualizationMode = types.HVM
	config.BootLoader = "/usr/lib/xen/boot/ovmf.bin"
	if err := kvmArm.CreateDomConfig(DefaultDomainName, config, types.DomainStatus{},
		diskStatuses, &aa, nil, swtpmCtrlSock, conf); err != nil {
		t.Errorf("CreateDomConfig failed %v", err)
	}
	defer os.Truncate(conf.Name(), 0)

	result, err := os.ReadFile(conf.Name())
	if err != nil {
		t.Errorf("reading conf file failed %v", err)
	}

	result = setStaticVsockCid(result)
	if string(result) != domConfigArm64() {
		t.Errorf("got an unexpected resulting config %s", string(result))
	}
}

func addNonExistingAdapter(config *types.DomainConfig, aa *types.AssignableAdapters) {
	config.IoAdapterList = append(config.IoAdapterList, types.IoAdapter{
		Type: types.IoNetEth,
		Name: "eth1",
	})

	aa.IoBundleList = append(aa.IoBundleList, types.IoBundle{
		Type:            types.IoNetEth,
		AssignmentGroup: "eth1-1",
		Phylabel:        "eth1",
		Ifname:          "eth1",
		PciLong:         "0000:f4:00.0",
		UsedByUUID:      config.UUIDandVersion.UUID,
	})
}

func qemuDisks() ([]types.DiskConfig, []types.DiskStatus) {
	dc := []types.DiskConfig{
		{Format: zconfig.Format_QCOW2, FileLocation: "/foo/bar.qcow2"},
		{Format: zconfig.Format_CONTAINER, FileLocation: "/foo/container"},
		{Format: zconfig.Format_RAW, FileLocation: "/foo/bar.raw"},
		{Format: zconfig.Format_RAW, FileLocation: "/foo/cd.iso"},
		{Format: zconfig.Format_CONTAINER, FileLocation: "/foo/volume"},
		{Format: zconfig.Format_RAW, WWN: "naa.000000000000000a"},
	}
	ds := []types.DiskStatus{
		{Format: zconfig.Format_QCOW2, FileLocation: "/foo/bar.qcow2", Devtype: "hdd"},
		{Format: zconfig.Format_CONTAINER, FileLocation: "/foo/container", Devtype: "9P"},
		{Format: zconfig.Format_RAW, FileLocation: "/foo/bar.raw", Devtype: "hdd"},
		{Format: zconfig.Format_RAW, FileLocation: "/foo/cd.iso", Devtype: "cdrom"},
		{Format: zconfig.Format_CONTAINER, FileLocation: "/foo/volume", Devtype: ""},
		{Format: zconfig.Format_RAW, WWN: "naa.000000000000000a", Devtype: "hdd"},
	}
	return dc, ds
}

func domainConfigAndAssignableAdapters(dcl []types.DiskConfig) (types.DomainConfig, types.AssignableAdapters) {
	id, err := uuid.NewV4()
	if err != nil {
		panic(fmt.Errorf("NewV4 failed: %v", err))
	}

	config := types.DomainConfig{
		UUIDandVersion: types.UUIDandVersion{UUID: id, Version: "1.0"},
		VmConfig: types.VmConfig{
			Kernel:     "/boot/kernel",
			Ramdisk:    "/boot/ramdisk",
			ExtraArgs:  "init=/bin/sh",
			Memory:     1024 * 1024 * 10,
			VCpus:      2,
			EnableVnc:  true,
			VncDisplay: 5,
			VncPasswd:  "rosebud",
		},
		GPUConfig:      "legacy",
		DiskConfigList: dcl,
		VifList: []types.VifConfig{
			{Bridge: "bn0", Mac: net.HardwareAddr{0x6a, 0x00, 0x03, 0x61, 0xa6, 0x90}, Vif: "nbu1x1"},
			{Bridge: "bn0", Mac: net.HardwareAddr{0x6a, 0x00, 0x03, 0x61, 0xa6, 0x91}, Vif: "nbu1x2"},
		},
		IoAdapterList: []types.IoAdapter{
			{Type: types.IoNetEth, Name: "eth0"},
			{Type: types.IoCom, Name: "COM1"},
			{Type: types.IoUSBDevice, Name: "USB1"},
		},
	}

	aa := types.AssignableAdapters{
		Initialized: true,
		IoBundleList: []types.IoBundle{
			{
				Type:            types.IoNetEth,
				AssignmentGroup: "eth0-1",
				Phylabel:        "eth0",
				Ifname:          "eth0",
				PciLong:         "0000:f3:00.0",
				UsedByUUID:      config.UUIDandVersion.UUID,
			},
			{
				Type:            types.IoCom,
				AssignmentGroup: "COM1",
				Phylabel:        "COM1",
				Ifname:          "COM1",
				Serial:          "/dev/ttyS0",
				UsedByUUID:      config.UUIDandVersion.UUID,
			},
			{
				Type:            types.IoUSBDevice,
				AssignmentGroup: "USB1",
				Phylabel:        "USB1:1",
				UsbAddr:         "1:1",
				UsedByUUID:      config.UUIDandVersion.UUID,
			},
		},
	}
	return config, aa
}

func qemuDisksLegacy() ([]types.DiskConfig, []types.DiskStatus) {
	dc := []types.DiskConfig{
		{Format: zconfig.Format_QCOW2, FileLocation: "/foo/bar.qcow2"},
		{Format: zconfig.Format_CONTAINER, FileLocation: "/foo/container"},
		{Format: zconfig.Format_RAW, FileLocation: "/foo/bar.raw"},
		{Format: zconfig.Format_RAW, FileLocation: "/foo/cd.iso"},
		{Format: zconfig.Format_CONTAINER, FileLocation: "/foo/volume"},
		{Format: zconfig.Format_RAW, WWN: "naa.000000000000000a"},
	}
	ds := []types.DiskStatus{
		{Format: zconfig.Format_QCOW2, FileLocation: "/foo/bar.qcow2", Devtype: "legacy"},
		{Format: zconfig.Format_CONTAINER, FileLocation: "/foo/container", Devtype: "9P"},
		{Format: zconfig.Format_RAW, FileLocation: "/foo/bar.raw", Devtype: "legacy"},
		{Format: zconfig.Format_RAW, FileLocation: "/foo/cd.iso", Devtype: "cdrom"},
		{Format: zconfig.Format_CONTAINER, FileLocation: "/foo/volume", Devtype: ""},
		{Format: zconfig.Format_RAW, WWN: "naa.000000000000000a", Devtype: "legacy"},
	}
	return dc, ds
}

func domConfigArm64() string {
	return fmt.Sprintf(`# This file is automatically generated by domainmgr
[msg]
  timestamp = "on"

[machine]
  type = "virt"
  dump-guest-core = "off"
  accel = "kvm:tcg"
  gic-version = "host"
  firmware = "/usr/lib/xen/boot/ovmf.bin"
  kernel = "/boot/kernel"
  initrd = "/boot/ramdisk"
  append = "init=/bin/sh"


[overcommit]
  mem-lock = "off"

[chardev "charmonitor"]
  backend = "socket"
  path = "/run/hypervisor/kvm/%s/qmp"
  server = "on"
  wait = "off"

[mon "monitor"]
  chardev = "charmonitor"
  mode = "control"

[chardev "charlistener"]
  backend = "socket"
  path = "/run/hypervisor/kvm/%s/listener.qmp"
  server = "on"
  wait = "off"

[mon "listener"]
  chardev = "charlistener"
  mode = "control"

[memory]
  size = "10240"

[smp-opts]
  cpus = "2"
  sockets = "1"
  cores = "2"
  threads = "1"

[device]
  driver = "virtio-serial"
  addr = "3"

[chardev "charserial0"]
  backend = "socket"
  mux = "on"
  path = "/run/hypervisor/kvm/%s/cons"
  server = "on"
  wait = "off"
  logfile = "/dev/fd/1"
  logappend = "on"

[device]
  driver = "virtconsole"
  chardev = "charserial0"
  name = "org.lfedge.eve.console.0"



[vnc "default"]
  vnc = "0.0.0.0:5"
  to = "99"
  password = "on"
[device "video0"]
  driver = "virtio-gpu-pci"
  bus = "pcie.0"
  addr = "0x1"
[device "pci.2"]
  driver = "pcie-root-port"
  port = "12"
  chassis = "2"
  bus = "pcie.0"
  addr = "0x2"

[device "usb"]
  driver = "qemu-xhci"
  p2 = "15"
  p3 = "15"
  bus = "pci.2"
  addr = "0x0"

[device "input0"]
  driver = "usb-kbd"
  bus = "usb.0"
  port = "1"

[device "input1"]
  driver = "usb-mouse"
  bus = "usb.0"
  port = "2"


[device "pci.4"]
  driver = "pcie-root-port"
  port = "14"
  chassis = "4"
  bus = "pcie.0"
  addr = "0x4"

[drive "drive-virtio-disk0"]
  file = "/foo/bar.qcow2"
  format = "qcow2"
  aio = "io_uring"
  cache = "writeback"
  if = "none"

[device "virtio-disk0"]
  driver = "virtio-blk-pci"
  scsi = "off"
  bus = "pci.4"
  addr = "0x0"
  drive = "drive-virtio-disk0"


[fsdev "fsdev1"]
  fsdriver = "local"
  security_model = "none"
  multidevs = "remap"
  path = "/foo/container"

[device "fs1"]
  driver = "virtio-9p-pci"
  fsdev = "fsdev1"
  mount_tag = "share_dir"
  addr = "0x5"


[device "pci.6"]
  driver = "pcie-root-port"
  port = "16"
  chassis = "6"
  bus = "pcie.0"
  addr = "0x6"

[drive "drive-virtio-disk2"]
  file = "/foo/bar.raw"
  format = "raw"
  aio = "io_uring"
  cache = "writeback"
  if = "none"

[device "virtio-disk2"]
  driver = "virtio-blk-pci"
  scsi = "off"
  bus = "pci.6"
  addr = "0x0"
  drive = "drive-virtio-disk2"


[drive "drive-sata0-3"]
  file = "/foo/cd.iso"
  format = "raw"
  if = "none"
  media = "cdrom"
  readonly = "on"

[device "sata0-0"]
  drive = "drive-sata0-3"
  driver = "usb-storage"



[device "pci.7"]
  driver = "pcie-root-port"
  port = "17"
  chassis = "7"
  bus = "pcie.0"
  addr = "0x7"

[device "vhost-disk4"]
  driver = "vhost-scsi-pci"
  max_sectors = "16384"
  wwpn = "naa.000000000000000a"
  bus = "pci.7"
  addr = "0x0"
  num_queues = "2"

[device "pci.8"]
  driver = "pcie-root-port"
  port = "18"
  chassis = "8"
  bus = "pcie.0"
  multifunction = "on"
  addr = "0x8"

[netdev "hostnet0"]
  type = "tap"
  ifname = "nbu1x1"
  br = "bn0"
  script = "/etc/xen/scripts/qemu-ifup"
  downscript = "no"
  vhost = "on"

[device "net0"]
  driver = "virtio-net-pci"
  netdev = "hostnet0"
  mac = "6a:00:03:61:a6:90"
  bus = "pci.8"
  addr = "0x0"

[device "pci.9"]
  driver = "pcie-root-port"
  port = "19"
  chassis = "9"
  bus = "pcie.0"
  multifunction = "on"
  addr = "0x9"

[netdev "hostnet1"]
  type = "tap"
  ifname = "nbu1x2"
  br = "bn0"
  script = "/etc/xen/scripts/qemu-ifup"
  downscript = "no"
  vhost = "on"

[device "net1"]
  driver = "virtio-net-pci"
  netdev = "hostnet1"
  mac = "6a:00:03:61:a6:91"
  bus = "pci.9"
  addr = "0x0"

[device "pci.10"]
  driver = "pcie-root-port"
  port = "110"
  chassis = "10"
  bus = "pcie.0"
  multifunction = "on"
  addr = "0xa"

[device]
  driver = "vfio-pci"
  host = "f3:00.0"
  bus = "pci.10"
  addr = "0x0"

[chardev "charserial-usr0"]
  backend = "serial"
  path = "/dev/ttyS0"

[device "serial-usr0"]
  driver = "pci-serial"
  chardev = "charserial-usr0"

[object "rng0"]
  qom-type = "rng-random"
  filename = "/dev/urandom"

[device "virtio-rng0"]
  driver = "virtio-rng-pci"
  rng = "rng0"
  max-bytes = "4096"
  period = "1000"

[device "eve-vsock0"]
  driver = "vhost-vsock-pci"
  disable-legacy = "on"
  guest-cid = "3"
`, DefaultDomainName, DefaultDomainName, DefaultDomainName)
}

func domConfigAmd64FML() string {
	return fmt.Sprintf(`# This file is automatically generated by domainmgr
[msg]
  timestamp = "on"

[machine]
  type = "pc-q35-3.1"
  dump-guest-core = "off"
  accel = "kvm"
  vmport = "off"
  kernel-irqchip = "on"
  kernel = "/boot/kernel"
  initrd = "/boot/ramdisk"
  append = "init=/bin/sh"

[global]
  driver = "kvm-pit"
  property = "lost_tick_policy"
  value = "delay"

[global]
  driver = "ICH9-LPC"
  property = "disable_s3"
  value = "1"

[global]
  driver = "ICH9-LPC"
  property = "disable_s4"
  value = "1"

[rtc]
  base = "localtime"
  driftfix = "slew"

[device]
  driver = "intel-iommu"
  caching-mode = "on"

[drive "drive-ovmf-code"]
  if = "pflash"
  format = "raw"
  readonly = "on"
  unit = "0"
  file = "/usr/lib/xen/boot/OVMF_CODE.fd"

[drive "drive-ovmf-vars"]
  if = "pflash"
  format = "raw"
  unit = "1"
  file = "/persist/vault/ovmf/%s_OVMF_VARS.fd"

[overcommit]
  mem-lock = "off"

[chardev "charmonitor"]
  backend = "socket"
  path = "/run/hypervisor/kvm/%s/qmp"
  server = "on"
  wait = "off"

[mon "monitor"]
  chardev = "charmonitor"
  mode = "control"

[chardev "charlistener"]
  backend = "socket"
  path = "/run/hypervisor/kvm/%s/listener.qmp"
  server = "on"
  wait = "off"

[mon "listener"]
  chardev = "charlistener"
  mode = "control"

[memory]
  size = "10240"

[smp-opts]
  cpus = "2"
  sockets = "1"
  cores = "2"
  threads = "1"

[device]
  driver = "virtio-serial"
  addr = "3"

[chardev "charserial0"]
  backend = "socket"
  mux = "on"
  path = "/run/hypervisor/kvm/%s/cons"
  server = "on"
  wait = "off"
  logfile = "/dev/fd/1"
  logappend = "on"

[device]
  driver = "virtconsole"
  chardev = "charserial0"
  name = "org.lfedge.eve.console.0"



[vnc "default"]
  vnc = "0.0.0.0:5"
  to = "99"
  password = "on"
[device "video0"]
  driver = "virtio-vga"
  bus = "pcie.0"
  addr = "0x1"
[device "pci.2"]
  driver = "pcie-root-port"
  port = "12"
  chassis = "2"
  bus = "pcie.0"
  addr = "0x2"

[device "usb"]
  driver = "qemu-xhci"
  p2 = "15"
  p3 = "15"
  bus = "pci.2"
  addr = "0x0"

[device "input0"]
  driver = "usb-tablet"
  bus = "usb.0"
  port = "1"


[device "pci.4"]
  driver = "pcie-root-port"
  port = "14"
  chassis = "4"
  bus = "pcie.0"
  addr = "0x4"

[drive "drive-virtio-disk0"]
  file = "/foo/bar.qcow2"
  format = "qcow2"
  aio = "io_uring"
  cache = "writeback"
  if = "none"

[device "virtio-disk0"]
  driver = "virtio-blk-pci"
  scsi = "off"
  bus = "pci.4"
  addr = "0x0"
  drive = "drive-virtio-disk0"


[fsdev "fsdev1"]
  fsdriver = "local"
  security_model = "none"
  multidevs = "remap"
  path = "/foo/container"

[device "fs1"]
  driver = "virtio-9p-pci"
  fsdev = "fsdev1"
  mount_tag = "share_dir"
  addr = "0x5"


[device "pci.6"]
  driver = "pcie-root-port"
  port = "16"
  chassis = "6"
  bus = "pcie.0"
  addr = "0x6"

[drive "drive-virtio-disk2"]
  file = "/foo/bar.raw"
  format = "raw"
  aio = "io_uring"
  cache = "writeback"
  if = "none"

[device "virtio-disk2"]
  driver = "virtio-blk-pci"
  scsi = "off"
  bus = "pci.6"
  addr = "0x0"
  drive = "drive-virtio-disk2"


[drive "drive-sata0-3"]
  file = "/foo/cd.iso"
  format = "raw"
  if = "none"
  media = "cdrom"
  readonly = "on"

[device "sata0-0"]
  drive = "drive-sata0-3"
  driver = "ide-cd"
  bus = "ide.0"


[device "pci.7"]
  driver = "pcie-root-port"
  port = "17"
  chassis = "7"
  bus = "pcie.0"
  addr = "0x7"

[device "vhost-disk4"]
  driver = "vhost-scsi-pci"
  max_sectors = "16384"
  wwpn = "naa.000000000000000a"
  bus = "pci.7"
  addr = "0x0"
  num_queues = "2"

[device "pci.8"]
  driver = "pcie-root-port"
  port = "18"
  chassis = "8"
  bus = "pcie.0"
  multifunction = "on"
  addr = "0x8"

[netdev "hostnet0"]
  type = "tap"
  ifname = "nbu1x1"
  br = "bn0"
  script = "/etc/xen/scripts/qemu-ifup"
  downscript = "no"
  vhost = "on"

[device "net0"]
  driver = "virtio-net-pci"
  netdev = "hostnet0"
  mac = "6a:00:03:61:a6:90"
  bus = "pci.8"
  addr = "0x0"

[device "pci.9"]
  driver = "pcie-root-port"
  port = "19"
  chassis = "9"
  bus = "pcie.0"
  multifunction = "on"
  addr = "0x9"

[netdev "hostnet1"]
  type = "tap"
  ifname = "nbu1x2"
  br = "bn0"
  script = "/etc/xen/scripts/qemu-ifup"
  downscript = "no"
  vhost = "on"

[device "net1"]
  driver = "virtio-net-pci"
  netdev = "hostnet1"
  mac = "6a:00:03:61:a6:91"
  bus = "pci.9"
  addr = "0x0"

[device "pci.10"]
  driver = "pcie-root-port"
  port = "110"
  chassis = "10"
  bus = "pcie.0"
  multifunction = "on"
  addr = "0xa"

[device]
  driver = "vfio-pci"
  host = "f3:00.0"
  bus = "pci.10"
  addr = "0x0"

[device "pci.11"]
  driver = "pcie-root-port"
  port = "111"
  chassis = "11"
  bus = "pcie.0"
  multifunction = "on"
  addr = "0xb"

[device]
  driver = "vfio-pci"
  host = "f4:00.0"
  bus = "pci.11"
  addr = "0x0"

[chardev "charserial-usr0"]
  backend = "serial"
  path = "/dev/ttyS0"

[device "serial-usr0"]
  driver = "isa-serial"
  chardev = "charserial-usr0"

[device "eve-vsock0"]
  driver = "vhost-vsock-pci"
  disable-legacy = "on"
  guest-cid = "3"
`, DefaultUUID, DefaultDomainName, DefaultDomainName, DefaultDomainName)
}

func domConfigAmd64Legacy() string {
	return fmt.Sprintf(`# This file is automatically generated by domainmgr
[msg]
  timestamp = "on"

[machine]
  type = "pc-q35-3.1"
  dump-guest-core = "off"
  accel = "kvm"
  vmport = "off"
  kernel-irqchip = "on"
  kernel = "/boot/kernel"
  initrd = "/boot/ramdisk"
  append = "init=/bin/sh"

[global]
  driver = "kvm-pit"
  property = "lost_tick_policy"
  value = "delay"

[global]
  driver = "ICH9-LPC"
  property = "disable_s3"
  value = "1"

[global]
  driver = "ICH9-LPC"
  property = "disable_s4"
  value = "1"

[rtc]
  base = "localtime"
  driftfix = "slew"

[device]
  driver = "intel-iommu"
  caching-mode = "on"

[overcommit]
  mem-lock = "off"

[chardev "charmonitor"]
  backend = "socket"
  path = "/run/hypervisor/kvm/%s/qmp"
  server = "on"
  wait = "off"

[mon "monitor"]
  chardev = "charmonitor"
  mode = "control"

[chardev "charlistener"]
  backend = "socket"
  path = "/run/hypervisor/kvm/%s/listener.qmp"
  server = "on"
  wait = "off"

[mon "listener"]
  chardev = "charlistener"
  mode = "control"

[memory]
  size = "10240"

[smp-opts]
  cpus = "2"
  sockets = "1"
  cores = "2"
  threads = "1"

[device]
  driver = "virtio-serial"
  addr = "3"

[chardev "charserial0"]
  backend = "socket"
  mux = "on"
  path = "/run/hypervisor/kvm/%s/cons"
  server = "on"
  wait = "off"
  logfile = "/dev/fd/1"
  logappend = "on"

[device]
  driver = "virtconsole"
  chardev = "charserial0"
  name = "org.lfedge.eve.console.0"



[vnc "default"]
  vnc = "0.0.0.0:5"
  to = "99"
  password = "on"
[device "video0"]
  driver = "virtio-vga"
  bus = "pcie.0"
  addr = "0x1"
[device "pci.2"]
  driver = "pcie-root-port"
  port = "12"
  chassis = "2"
  bus = "pcie.0"
  addr = "0x2"

[device "usb"]
  driver = "qemu-xhci"
  p2 = "15"
  p3 = "15"
  bus = "pci.2"
  addr = "0x0"

[device "input0"]
  driver = "usb-tablet"
  bus = "usb.0"
  port = "1"


[device "pci.4"]
  driver = "pcie-root-port"
  port = "14"
  chassis = "4"
  bus = "pcie.0"
  addr = "0x4"

[drive "drive-virtio-disk0"]
  file = "/foo/bar.qcow2"
  format = "qcow2"
  aio = "io_uring"
  cache = "writeback"
  if = "none"

[device "ahci.4"]
  bus = "pci.4"
  driver = "ahci"

[device "ahci-disk0"]
  driver = "ide-hd"
  bus = "ahci.4.0"
  drive = "drive-virtio-disk0"


[fsdev "fsdev1"]
  fsdriver = "local"
  security_model = "none"
  multidevs = "remap"
  path = "/foo/container"

[device "fs1"]
  driver = "virtio-9p-pci"
  fsdev = "fsdev1"
  mount_tag = "share_dir"
  addr = "0x5"


[device "pci.6"]
  driver = "pcie-root-port"
  port = "16"
  chassis = "6"
  bus = "pcie.0"
  addr = "0x6"

[drive "drive-virtio-disk2"]
  file = "/foo/bar.raw"
  format = "raw"
  aio = "io_uring"
  cache = "writeback"
  if = "none"

[device "ahci.6"]
  bus = "pci.6"
  driver = "ahci"

[device "ahci-disk2"]
  driver = "ide-hd"
  bus = "ahci.6.0"
  drive = "drive-virtio-disk2"


[drive "drive-sata0-3"]
  file = "/foo/cd.iso"
  format = "raw"
  if = "none"
  media = "cdrom"
  readonly = "on"

[device "sata0-0"]
  drive = "drive-sata0-3"
  driver = "ide-cd"
  bus = "ide.0"


[device "pci.7"]
  driver = "pcie-root-port"
  port = "17"
  chassis = "7"
  bus = "pcie.0"
  addr = "0x7"

[device "vhost-disk4"]
  driver = "vhost-scsi-pci"
  max_sectors = "16384"
  wwpn = "naa.000000000000000a"
  bus = "pci.7"
  addr = "0x0"
  num_queues = "2"

[device "pci.8"]
  driver = "pcie-root-port"
  port = "18"
  chassis = "8"
  bus = "pcie.0"
  multifunction = "on"
  addr = "0x8"

[netdev "hostnet0"]
  type = "tap"
  ifname = "nbu1x1"
  br = "bn0"
  script = "/etc/xen/scripts/qemu-ifup"
  downscript = "no"

[device "net0"]
  driver = "e1000"
  netdev = "hostnet0"
  mac = "6a:00:03:61:a6:90"
  bus = "pci.8"
  addr = "0x0"

[device "pci.9"]
  driver = "pcie-root-port"
  port = "19"
  chassis = "9"
  bus = "pcie.0"
  multifunction = "on"
  addr = "0x9"

[netdev "hostnet1"]
  type = "tap"
  ifname = "nbu1x2"
  br = "bn0"
  script = "/etc/xen/scripts/qemu-ifup"
  downscript = "no"

[device "net1"]
  driver = "e1000"
  netdev = "hostnet1"
  mac = "6a:00:03:61:a6:91"
  bus = "pci.9"
  addr = "0x0"

[device "pci.10"]
  driver = "pcie-root-port"
  port = "110"
  chassis = "10"
  bus = "pcie.0"
  multifunction = "on"
  addr = "0xa"

[device]
  driver = "vfio-pci"
  host = "f3:00.0"
  bus = "pci.10"
  addr = "0x0"

[chardev "charserial-usr0"]
  backend = "serial"
  path = "/dev/ttyS0"

[device "serial-usr0"]
  driver = "isa-serial"
  chardev = "charserial-usr0"

[device "eve-vsock0"]
  driver = "vhost-vsock-pci"
  disable-legacy = "on"
  guest-cid = "3"
`, DefaultDomainName, DefaultDomainName, DefaultDomainName)
}

func domConfigAmd64() string {
	return fmt.Sprintf(`# This file is automatically generated by domainmgr
[msg]
  timestamp = "on"

[machine]
  type = "pc-q35-3.1"
  dump-guest-core = "off"
  accel = "kvm"
  vmport = "off"
  kernel-irqchip = "on"
  kernel = "/boot/kernel"
  initrd = "/boot/ramdisk"
  append = "init=/bin/sh"

[global]
  driver = "kvm-pit"
  property = "lost_tick_policy"
  value = "delay"

[global]
  driver = "ICH9-LPC"
  property = "disable_s3"
  value = "1"

[global]
  driver = "ICH9-LPC"
  property = "disable_s4"
  value = "1"

[rtc]
  base = "localtime"
  driftfix = "slew"

[device]
  driver = "intel-iommu"
  caching-mode = "on"

[overcommit]
  mem-lock = "off"

[chardev "charmonitor"]
  backend = "socket"
  path = "/run/hypervisor/kvm/%s/qmp"
  server = "on"
  wait = "off"

[mon "monitor"]
  chardev = "charmonitor"
  mode = "control"

[chardev "charlistener"]
  backend = "socket"
  path = "/run/hypervisor/kvm/%s/listener.qmp"
  server = "on"
  wait = "off"

[mon "listener"]
  chardev = "charlistener"
  mode = "control"

[memory]
  size = "10240"

[smp-opts]
  cpus = "2"
  sockets = "1"
  cores = "2"
  threads = "1"

[device]
  driver = "virtio-serial"
  addr = "3"

[chardev "charserial0"]
  backend = "socket"
  mux = "on"
  path = "/run/hypervisor/kvm/%s/cons"
  server = "on"
  wait = "off"
  logfile = "/dev/fd/1"
  logappend = "on"

[device]
  driver = "virtconsole"
  chardev = "charserial0"
  name = "org.lfedge.eve.console.0"



[vnc "default"]
  vnc = "0.0.0.0:5"
  to = "99"
  password = "on"
[device "video0"]
  driver = "virtio-vga"
  bus = "pcie.0"
  addr = "0x1"
[device "pci.2"]
  driver = "pcie-root-port"
  port = "12"
  chassis = "2"
  bus = "pcie.0"
  addr = "0x2"

[device "usb"]
  driver = "qemu-xhci"
  p2 = "15"
  p3 = "15"
  bus = "pci.2"
  addr = "0x0"

[device "input0"]
  driver = "usb-tablet"
  bus = "usb.0"
  port = "1"


[device "pci.4"]
  driver = "pcie-root-port"
  port = "14"
  chassis = "4"
  bus = "pcie.0"
  addr = "0x4"

[drive "drive-virtio-disk0"]
  file = "/foo/bar.qcow2"
  format = "qcow2"
  aio = "io_uring"
  cache = "writeback"
  if = "none"

[device "virtio-disk0"]
  driver = "virtio-blk-pci"
  scsi = "off"
  bus = "pci.4"
  addr = "0x0"
  drive = "drive-virtio-disk0"


[fsdev "fsdev1"]
  fsdriver = "local"
  security_model = "none"
  multidevs = "remap"
  path = "/foo/container"

[device "fs1"]
  driver = "virtio-9p-pci"
  fsdev = "fsdev1"
  mount_tag = "share_dir"
  addr = "0x5"


[device "pci.6"]
  driver = "pcie-root-port"
  port = "16"
  chassis = "6"
  bus = "pcie.0"
  addr = "0x6"

[drive "drive-virtio-disk2"]
  file = "/foo/bar.raw"
  format = "raw"
  aio = "io_uring"
  cache = "writeback"
  if = "none"

[device "virtio-disk2"]
  driver = "virtio-blk-pci"
  scsi = "off"
  bus = "pci.6"
  addr = "0x0"
  drive = "drive-virtio-disk2"


[drive "drive-sata0-3"]
  file = "/foo/cd.iso"
  format = "raw"
  if = "none"
  media = "cdrom"
  readonly = "on"

[device "sata0-0"]
  drive = "drive-sata0-3"
  driver = "ide-cd"
  bus = "ide.0"


[device "pci.7"]
  driver = "pcie-root-port"
  port = "17"
  chassis = "7"
  bus = "pcie.0"
  addr = "0x7"

[device "vhost-disk4"]
  driver = "vhost-scsi-pci"
  max_sectors = "16384"
  wwpn = "naa.000000000000000a"
  bus = "pci.7"
  addr = "0x0"
  num_queues = "2"

[device "pci.8"]
  driver = "pcie-root-port"
  port = "18"
  chassis = "8"
  bus = "pcie.0"
  multifunction = "on"
  addr = "0x8"

[netdev "hostnet0"]
  type = "tap"
  ifname = "nbu1x1"
  br = "bn0"
  script = "/etc/xen/scripts/qemu-ifup"
  downscript = "no"
  vhost = "on"

[device "net0"]
  driver = "virtio-net-pci"
  netdev = "hostnet0"
  mac = "6a:00:03:61:a6:90"
  bus = "pci.8"
  addr = "0x0"

[device "pci.9"]
  driver = "pcie-root-port"
  port = "19"
  chassis = "9"
  bus = "pcie.0"
  multifunction = "on"
  addr = "0x9"

[netdev "hostnet1"]
  type = "tap"
  ifname = "nbu1x2"
  br = "bn0"
  script = "/etc/xen/scripts/qemu-ifup"
  downscript = "no"
  vhost = "on"

[device "net1"]
  driver = "virtio-net-pci"
  netdev = "hostnet1"
  mac = "6a:00:03:61:a6:91"
  bus = "pci.9"
  addr = "0x0"

[device "pci.10"]
  driver = "pcie-root-port"
  port = "110"
  chassis = "10"
  bus = "pcie.0"
  multifunction = "on"
  addr = "0xa"

[device]
  driver = "vfio-pci"
  host = "f3:00.0"
  bus = "pci.10"
  addr = "0x0"

[chardev "charserial-usr0"]
  backend = "serial"
  path = "/dev/ttyS0"

[device "serial-usr0"]
  driver = "isa-serial"
  chardev = "charserial-usr0"

[device "eve-vsock0"]
  driver = "vhost-vsock-pci"
  disable-legacy = "on"
  guest-cid = "3"
`, DefaultDomainName, DefaultDomainName, DefaultDomainName)
}

func domConfigContainerVNC() string {
	return fmt.Sprintf(`# This file is automatically generated by domainmgr
[msg]
  timestamp = "on"

[machine]
  type = "pc-q35-3.1"
  dump-guest-core = "off"
  accel = "kvm"
  vmport = "off"
  kernel-irqchip = "on"
  kernel = "/boot/kernel"
  initrd = "/boot/ramdisk"
  append = "init=/bin/sh"

[global]
  driver = "kvm-pit"
  property = "lost_tick_policy"
  value = "delay"

[global]
  driver = "ICH9-LPC"
  property = "disable_s3"
  value = "1"

[global]
  driver = "ICH9-LPC"
  property = "disable_s4"
  value = "1"

[rtc]
  base = "localtime"
  driftfix = "slew"

[device]
  driver = "intel-iommu"
  caching-mode = "on"

[overcommit]
  mem-lock = "off"

[chardev "charmonitor"]
  backend = "socket"
  path = "/run/hypervisor/kvm/%s/qmp"
  server = "on"
  wait = "off"

[mon "monitor"]
  chardev = "charmonitor"
  mode = "control"

[chardev "charlistener"]
  backend = "socket"
  path = "/run/hypervisor/kvm/%s/listener.qmp"
  server = "on"
  wait = "off"

[mon "listener"]
  chardev = "charlistener"
  mode = "control"

[memory]
  size = "10240"

[smp-opts]
  cpus = "2"
  sockets = "1"
  cores = "2"
  threads = "1"

[device]
  driver = "virtio-serial"
  addr = "3"

[chardev "charserial0"]
  backend = "socket"
  mux = "on"
  path = "/run/hypervisor/kvm/%s/cons"
  server = "on"
  wait = "off"
  logfile = "/dev/fd/1"
  logappend = "on"

[device]
  driver = "virtconsole"
  chardev = "charserial0"
  name = "org.lfedge.eve.console.0"

[chardev "charserial1"]
  backend = "socket"
  path = "/run/hypervisor/kvm/%s/shim-cons"
  server = "on"
  wait = "off"

[chardev "charserial2"]
  backend = "vc"

[chardev "charhub0"]
  backend = "hub"
  chardevs.0 = "charserial1"
  chardevs.1 = "charserial2"
  logfile = "/dev/fd/1"
  logappend = "on"

[device]
  driver = "virtconsole"
  chardev = "charhub0"
  name = "org.lfedge.eve.console.shim"


[vnc "default"]
  vnc = "0.0.0.0:5"
  to = "99"
  password = "on"
[device "video0"]
  driver = "virtio-vga"
  bus = "pcie.0"
  addr = "0x1"
[device "pci.2"]
  driver = "pcie-root-port"
  port = "12"
  chassis = "2"
  bus = "pcie.0"
  addr = "0x2"

[device "usb"]
  driver = "qemu-xhci"
  p2 = "15"
  p3 = "15"
  bus = "pci.2"
  addr = "0x0"

[device "input0"]
  driver = "usb-tablet"
  bus = "usb.0"
  port = "1"


[fsdev "fsdev0"]
  fsdriver = "local"
  security_model = "none"
  multidevs = "remap"
  path = "/foo/container"

[device "fs0"]
  driver = "virtio-9p-pci"
  fsdev = "fsdev0"
  mount_tag = "share_dir"
  addr = "0x4"


[device "pci.5"]
  driver = "pcie-root-port"
  port = "15"
  chassis = "5"
  bus = "pcie.0"
  addr = "0x5"

[drive "drive-virtio-disk1"]
  file = "/foo/bar.raw"
  format = "raw"
  aio = "io_uring"
  cache = "writeback"
  if = "none"

[device "virtio-disk1"]
  driver = "virtio-blk-pci"
  scsi = "off"
  bus = "pci.5"
  addr = "0x0"
  drive = "drive-virtio-disk1"


[drive "drive-sata0-2"]
  file = "/foo/cd.iso"
  format = "raw"
  if = "none"
  media = "cdrom"
  readonly = "on"

[device "sata0-0"]
  drive = "drive-sata0-2"
  driver = "ide-cd"
  bus = "ide.0"


[device "pci.6"]
  driver = "pcie-root-port"
  port = "16"
  chassis = "6"
  bus = "pcie.0"
  addr = "0x6"

[device "vhost-disk3"]
  driver = "vhost-scsi-pci"
  max_sectors = "16384"
  wwpn = "naa.000000000000000a"
  bus = "pci.6"
  addr = "0x0"
  num_queues = "2"

[device "pci.7"]
  driver = "pcie-root-port"
  port = "17"
  chassis = "7"
  bus = "pcie.0"
  multifunction = "on"
  addr = "0x7"

[netdev "hostnet0"]
  type = "tap"
  ifname = "nbu1x1"
  br = "bn0"
  script = "/etc/xen/scripts/qemu-ifup"
  downscript = "no"
  vhost = "on"

[device "net0"]
  driver = "virtio-net-pci"
  netdev = "hostnet0"
  mac = "6a:00:03:61:a6:90"
  bus = "pci.7"
  addr = "0x0"

[device "pci.8"]
  driver = "pcie-root-port"
  port = "18"
  chassis = "8"
  bus = "pcie.0"
  multifunction = "on"
  addr = "0x8"

[netdev "hostnet1"]
  type = "tap"
  ifname = "nbu1x2"
  br = "bn0"
  script = "/etc/xen/scripts/qemu-ifup"
  downscript = "no"
  vhost = "on"

[device "net1"]
  driver = "virtio-net-pci"
  netdev = "hostnet1"
  mac = "6a:00:03:61:a6:91"
  bus = "pci.8"
  addr = "0x0"

[device "pci.9"]
  driver = "pcie-root-port"
  port = "19"
  chassis = "9"
  bus = "pcie.0"
  multifunction = "on"
  addr = "0x9"

[device]
  driver = "vfio-pci"
  host = "f3:00.0"
  bus = "pci.9"
  addr = "0x0"

[chardev "charserial-usr0"]
  backend = "serial"
  path = "/dev/ttyS0"

[device "serial-usr0"]
  driver = "isa-serial"
  chardev = "charserial-usr0"

[device "eve-vsock0"]
  driver = "vhost-vsock-pci"
  disable-legacy = "on"
  guest-cid = "3"
`, DefaultDomainName, DefaultDomainName, DefaultDomainName, DefaultDomainName)
}

func TestCreateDom(t *testing.T) {
	if exec.Command("qemu-system-x86_64", "--version").Run() != nil {
		// skipping this test since we're clearly not in a presence of qemu
		return
	}
	id, err := uuid.NewV4()
	if err != nil {
		t.Errorf("NewV4 failed: %v", err)
	}
	config := types.DomainConfig{
		UUIDandVersion: types.UUIDandVersion{UUID: id, Version: "1.0"},
		VmConfig: types.VmConfig{
			Kernel:             "/boot/kernel",
			Ramdisk:            "/boot/ramdisk",
			ExtraArgs:          "init=/bin/sh",
			Memory:             1024 * 1024 * 10,
			VCpus:              2,
			VncDisplay:         5,
			VncPasswd:          "rosebud",
			VirtualizationMode: types.HVM,
		},
		GPUConfig: "legacy",
		VifList: []types.VifConfig{
			{Bridge: "bn0", Mac: net.HardwareAddr{0x6a, 0x00, 0x03, 0x61, 0xa6, 0x90}, Vif: "nbu1x1"},
			{Bridge: "bn0", Mac: net.HardwareAddr{0x6a, 0x00, 0x03, 0x61, 0xa6, 0x91}, Vif: "nbu1x2"},
		},
		IoAdapterList: []types.IoAdapter{
			{Type: types.IoNetEth, Name: "eth0"},
			{Type: types.IoCom, Name: "COM1"},
		},
	}
	os.RemoveAll(kvmStateDir)

	conf, err := os.CreateTemp("/tmp/", "config")
	if err != nil {
		t.Errorf("Can't create config file for a domain %v", err)
	} else {
		defer os.Remove(conf.Name())
	}
	os.WriteFile(conf.Name(), []byte(fmt.Sprintf(
		`# This file is automatically generated by domainmgr
[msg]
  timestamp = "on"

[machine]
  type = "pc-q35-3.1"
  vmport = "off"
  dump-guest-core = "off"

[global]
  driver = "ICH9-LPC"
  property = "disable_s3"
  value = "1"

[global]
  driver = "ICH9-LPC"
  property = "disable_s4"
  value = "1"

[overcommit]
  mem-lock = "off"

[rtc]
  base = "localtime"
  driftfix = "slew"

[chardev "charmonitor"]
  backend = "socket"
  path = "/run/hypervisor/kvm/%s/qmp"
  server = "on"
  wait = "off"

[chardev "charlistener"]
  backend = "socket"
  path = "/run/hypervisor/kvm/%s/listener.qmp"
  server = "on"
  wait = "off"

[mon "listener"]
  chardev = "charlistener"
  mode = "control"

[mon "monitor"]
  chardev = "charmonitor"
  mode = "control"

[memory]
  size = "1024"

[smp-opts]
  cpus = "2"
  sockets = "1"
  cores = "2"
  threads = "1"`, DefaultDomainName, DefaultDomainName)), 0777)

	if kvmIntel.ctrdClient == nil {
		t.Skipf("test must be run on a system with a functional containerd")
	}

	if _, err := kvmIntel.Task(testDom).Create("test", conf.Name(), &config); err != nil {
		t.Errorf("Create domain config failed %v", err)
	}

	state, err := os.Open(kvmStateDir + "/test")
	if err != nil {
		t.Errorf("can't open stat dir for test domain %v", err)
	}

	names, err := state.Readdirnames(0)
	if err != nil || len(names) != 3 {
		t.Errorf("can't read stat dir for test domain or got unexpected content %v", err)
	}

	for _, e := range names {
		if _, found := map[string]bool{"pid": true, "qmp": true, "cons": true}[e]; !found {
			t.Errorf("got an unexpected entry %s in the stat dir for domain test", e)
		}
	}

	if err := kvmIntel.Task(testDom).Start("test"); err != nil {
		t.Errorf("Start domain failed %v", err)
	}

	if err := kvmIntel.Task(testDom).Stop("test", true); err != nil {
		t.Errorf("Stop domain failed %v", err)
	}

	if err := kvmIntel.Task(testDom).Delete("test"); err != nil {
		t.Errorf("Delete domain failed %v", err)
	}

	if err := kvmIntel.Task(testDom).Cleanup("test"); err != nil {
		t.Errorf("Cleanup domain failed %v", err)
	}

	state, err = os.Open(kvmStateDir)
	if err != nil {
		t.Errorf("can't open stat dir for test domain %v", err)
	}

	names, err = state.Readdirnames(0)
	if err != nil || len(names) != 0 {
		t.Errorf("can't read stat dir for test domain or state dir is not empty after all domains are gone %v", err)
	}
}

func TestCreateDomConfigContainerVNC(t *testing.T) {
	t.Parallel()

	conf, err := os.CreateTemp("/tmp", "config")
	if err != nil {
		t.Errorf("Can't create config file for a domain %v", err)
	}
	defer os.Remove(conf.Name())

	diskConfigs, diskStatuses := qemuDisks()
	// remove the first disk, so that the container disk is the first one, resulting in IsOciContainer being true
	diskConfigs = diskConfigs[1:]
	diskStatuses = diskStatuses[1:]

	config, aa := domainConfigAndAssignableAdapters(diskConfigs)
	// enable VNC and VNC for shim VM
	config.VmConfig.EnableVnc = true
	config.VmConfig.EnableVncShimVM = true
	if err := kvmIntel.CreateDomConfig(DefaultDomainName, config, types.DomainStatus{},
		diskStatuses, &aa, nil, swtpmCtrlSock, conf); err != nil {
		t.Errorf("CreateDomConfig failed %v", err)
	}
	defer os.Truncate(conf.Name(), 0)

	result, err := os.ReadFile(conf.Name())
	if err != nil {
		t.Errorf("reading conf file failed %v", err)
	}

	result = setStaticVsockCid(result)
	if string(result) != domConfigContainerVNC() {
		t.Errorf("got an unexpected resulting config %s", string(result))
	}
}

func expectedMultifunctionDevice() string {
	return `
[device "pci.0"]
  driver = "pcie-root-port"
  port = "10"
  chassis = "0"
  bus = "pcie.0"
  multifunction = "on"
  addr = "0x0"

[device]
  driver = "vfio-pci"
  host = "00:0a.0"
  bus = "pci.0"
  addr = "0x0"

[device "pci.1"]
  driver = "pcie-root-port"
  port = "11"
  chassis = "1"
  bus = "pcie.0"
  multifunction = "on"
  addr = "0x1"

[device "pcie-bridge.1"]
  driver = "pcie-pci-bridge"
  bus = "pci.1"
  addr = "0x0"

[device]
  driver = "vfio-pci"
  host = "00:0d.0"
  bus = "pcie-bridge.1"
  addr = "0x1"

[device "pci.2"]
  driver = "pcie-root-port"
  port = "12"
  chassis = "2"
  bus = "pcie.0"
  multifunction = "on"
  addr = "0x2"

[device]
  driver = "vfio-pci"
  host = "00:0b.0"
  bus = "pci.2"
  addr = "0x0"

[device]
  driver = "vfio-pci"
  host = "00:0d.2"
  bus = "pcie-bridge.1"
  addr = "0x2"
`
}

func TestPCIAssignmentsTemplateFillMultifunctionDevice(t *testing.T) {
	pciAssignments := []pciDevice{
		{
			ioBundle: types.IoBundle{
				PciLong: "0000:00:0a.0",
				Type:    0,
			},
		},
		{
			ioBundle: types.IoBundle{
				PciLong: "0000:00:0d.0",
				Type:    0,
			},
		},
		{
			ioBundle: types.IoBundle{
				PciLong: "0000:00:0b.0",
				Type:    0,
			},
		},
		{
			ioBundle: types.IoBundle{
				PciLong: "0000:00:0d.2",
				Type:    0,
			},
		},
	}

	wr := bytes.Buffer{}
	multifunctionDevices := multifunctionDevGroup(pciAssignments)
	addrAllocator := pciAddressAllocator{
		pciAssignments:       pciAssignments,
		multifunctionDevices: multifunctionDevices,
	}
	if err := addrAllocator.allocate(); err != nil {
		t.Error(err)
	}

	p := pciAssignmentsTemplateFiller{
		multifunctionDevices: multifunctionDevices,
		file:                 &wr,
	}
	p.do(pciAssignments)

	if wr.String() != expectedMultifunctionDevice() {
		t.Fatalf("not equal, diff: \n%s\ncomplete:\n%s", cmp.Diff(wr.String(), expectedMultifunctionDevice()), wr.String())
	}
}

func TestConvertToMultifunctionPCIDevices(t *testing.T) {
	pciAssignments := []pciDevice{
		{
			ioBundle: types.IoBundle{
				PciLong: "0000:00:0d.0",
				Type:    0,
			},
		},
		{
			ioBundle: types.IoBundle{
				PciLong: "0000:00:aa.8",
				Type:    0,
			},
		},
		{
			ioBundle: types.IoBundle{
				PciLong: "0000:00:0d.2",
				Type:    0,
			},
		},
		{
			ioBundle: types.IoBundle{
				PciLong: "0000:00:0d.f",
				Type:    0,
			},
		},
	}

	mds := multifunctionDevGroup(pciAssignments)

	if len(mds) != 2 {
		t.Fatalf("expected two multifunction pci assignments, but got %d", len(mds))
	}

	t.Log(mds)
	for i, pci := range []string{"0000:00:0d.0", "0000:00:0d.2", "0000:00:0d.f"} {
		functionPCIDev := mds["0000:00:0d"].devs[i].ioBundle.PciLong
		if functionPCIDev != pci {
			t.Logf("expected %s got %s", pci, functionPCIDev)
			t.Fail()
		}
	}

	if len(mds["0000:00:aa"].devs) != 1 {
		t.Fatal("expected one device")
	}
}

func TestPCIAddressAllocator(t *testing.T) {
	g := NewGomegaWithT(t)
	virtualNetworks := []virtualNetwork{
		{
			VifConfig: types.VifConfig{
				Bridge:   "br1",
				Vif:      "nbu1x1",
				Mac:      net.HardwareAddr{0x02, 0x16, 0x3e, 0x00, 0x00, 0x01},
				MTU:      1500,
				VifOrder: 1,
			},
			networkID: 0,
		},
		{
			VifConfig: types.VifConfig{
				Bridge:   "br2",
				Vif:      "nbu2x1",
				Mac:      net.HardwareAddr{0x02, 0x16, 0x3e, 0x00, 0x00, 0x02},
				MTU:      1500,
				VifOrder: 4,
			},
			networkID: 1,
		},
	}
	pciAssignments := []pciDevice{
		{
			ioBundle: types.IoBundle{
				PciLong: "0000:06:00.0",
				Type:    types.IoNetEth,
			},
			netIntfOrder: 2,
		},
		{
			ioBundle: types.IoBundle{
				PciLong: "0000:00:15.0",
				Type:    types.IoUSBController,
			},
		},
		{
			ioBundle: types.IoBundle{
				PciLong: "0000:06:00.2",
				Type:    types.IoOther,
			},
		},
		{
			ioBundle: types.IoBundle{
				PciLong: "0000:06:00.1",
				Type:    types.IoNetEth,
			},
			netIntfOrder: 3,
		},
		{
			ioBundle: types.IoBundle{
				PciLong: "0000:08:00.0",
				Type:    types.IoNetWWAN,
			},
			netIntfOrder: 0,
		},
	}
	multifunctionDevices := multifunctionDevGroup(pciAssignments)
	g.Expect(multifunctionDevices).To(HaveLen(3))
	addrAllocator := pciAddressAllocator{
		pciAssignments:       pciAssignments,
		virtualNetworks:      virtualNetworks,
		multifunctionDevices: multifunctionDevices,
		firstFreePCIID:       5,
		// First test the legacy order.
		enforceNetInterfaceOrder: false,
	}
	err := addrAllocator.allocate()
	g.Expect(err).ToNot(HaveOccurred())

	g.Expect(virtualNetworks[0].pciDeviceID).To(Equal(5))
	g.Expect(virtualNetworks[1].pciDeviceID).To(Equal(6))
	g.Expect(pciAssignments[0].pciBridgeID).To(Equal(7))
	g.Expect(pciAssignments[0].pciDeviceID).To(Equal(1))
	g.Expect(pciAssignments[1].pciBridgeID).To(Equal(0))
	g.Expect(pciAssignments[1].pciDeviceID).To(Equal(8))
	g.Expect(pciAssignments[2].pciBridgeID).To(Equal(7))
	g.Expect(pciAssignments[2].pciDeviceID).To(Equal(2))
	g.Expect(pciAssignments[3].pciBridgeID).To(Equal(7))
	g.Expect(pciAssignments[3].pciDeviceID).To(Equal(3))
	g.Expect(pciAssignments[4].pciBridgeID).To(Equal(0))
	g.Expect(pciAssignments[4].pciDeviceID).To(Equal(9))

	// Check generated config with the legacy order.
	buffer := bytes.Buffer{}
	vnFiller := virtNetworkTemplateFiller{
		file: &buffer,
	}
	err = vnFiller.do(virtualNetworks, types.HVM)
	g.Expect(err).ToNot(HaveOccurred())
	paFiller := pciAssignmentsTemplateFiller{
		multifunctionDevices: multifunctionDevices,
		file:                 &buffer,
	}
	err = paFiller.do(pciAssignments)
	g.Expect(err).ToNot(HaveOccurred())
	expectedConfig := `
[device "pci.5"]
  driver = "pcie-root-port"
  port = "15"
  chassis = "5"
  bus = "pcie.0"
  multifunction = "on"
  addr = "0x5"

[netdev "hostnet0"]
  type = "tap"
  ifname = "nbu1x1"
  br = "br1"
  script = "/etc/xen/scripts/qemu-ifup"
  downscript = "no"
  vhost = "on"

[device "net0"]
  driver = "virtio-net-pci"
  netdev = "hostnet0"
  mac = "02:16:3e:00:00:01"
  bus = "pci.5"
  addr = "0x0"
  host_mtu = "1500"

[device "pci.6"]
  driver = "pcie-root-port"
  port = "16"
  chassis = "6"
  bus = "pcie.0"
  multifunction = "on"
  addr = "0x6"

[netdev "hostnet1"]
  type = "tap"
  ifname = "nbu2x1"
  br = "br2"
  script = "/etc/xen/scripts/qemu-ifup"
  downscript = "no"
  vhost = "on"

[device "net1"]
  driver = "virtio-net-pci"
  netdev = "hostnet1"
  mac = "02:16:3e:00:00:02"
  bus = "pci.6"
  addr = "0x0"
  host_mtu = "1500"

[device "pci.7"]
  driver = "pcie-root-port"
  port = "17"
  chassis = "7"
  bus = "pcie.0"
  multifunction = "on"
  addr = "0x7"

[device "pcie-bridge.7"]
  driver = "pcie-pci-bridge"
  bus = "pci.7"
  addr = "0x0"

[device]
  driver = "vfio-pci"
  host = "06:00.0"
  bus = "pcie-bridge.7"
  addr = "0x1"

[device "pci.8"]
  driver = "pcie-root-port"
  port = "18"
  chassis = "8"
  bus = "pcie.0"
  multifunction = "on"
  addr = "0x8"

[device]
  driver = "vfio-pci"
  host = "00:15.0"
  bus = "pci.8"
  addr = "0x0"

[device]
  driver = "vfio-pci"
  host = "06:00.2"
  bus = "pcie-bridge.7"
  addr = "0x2"

[device]
  driver = "vfio-pci"
  host = "06:00.1"
  bus = "pcie-bridge.7"
  addr = "0x3"

[device "pci.9"]
  driver = "pcie-root-port"
  port = "19"
  chassis = "9"
  bus = "pcie.0"
  multifunction = "on"
  addr = "0x9"

[device]
  driver = "vfio-pci"
  host = "08:00.0"
  bus = "pci.9"
  addr = "0x0"
`
	g.Expect(buffer.String()).To(Equal(expectedConfig))

	// Test enforced user-defined network interface order.
	addrAllocator.enforceNetInterfaceOrder = true
	err = addrAllocator.allocate()
	g.Expect(err).ToNot(HaveOccurred())

	g.Expect(virtualNetworks[0].pciDeviceID).To(Equal(6))
	g.Expect(virtualNetworks[1].pciDeviceID).To(Equal(8))
	g.Expect(pciAssignments[0].pciBridgeID).To(Equal(7))
	g.Expect(pciAssignments[0].pciDeviceID).To(Equal(1))
	g.Expect(pciAssignments[1].pciBridgeID).To(Equal(0))
	g.Expect(pciAssignments[1].pciDeviceID).To(Equal(9))
	g.Expect(pciAssignments[2].pciBridgeID).To(Equal(7))
	g.Expect(pciAssignments[2].pciDeviceID).To(Equal(3))
	g.Expect(pciAssignments[3].pciBridgeID).To(Equal(7))
	g.Expect(pciAssignments[3].pciDeviceID).To(Equal(2))
	g.Expect(pciAssignments[4].pciBridgeID).To(Equal(0))
	g.Expect(pciAssignments[4].pciDeviceID).To(Equal(5))

	// Check generated config with the user-defined order.
	buffer.Reset()
	err = vnFiller.do(virtualNetworks, types.HVM)
	g.Expect(err).ToNot(HaveOccurred())
	err = paFiller.do(pciAssignments)
	g.Expect(err).ToNot(HaveOccurred())
	expectedConfig = `
[device "pci.6"]
  driver = "pcie-root-port"
  port = "16"
  chassis = "6"
  bus = "pcie.0"
  multifunction = "on"
  addr = "0x6"

[netdev "hostnet0"]
  type = "tap"
  ifname = "nbu1x1"
  br = "br1"
  script = "/etc/xen/scripts/qemu-ifup"
  downscript = "no"
  vhost = "on"

[device "net0"]
  driver = "virtio-net-pci"
  netdev = "hostnet0"
  mac = "02:16:3e:00:00:01"
  bus = "pci.6"
  addr = "0x0"
  host_mtu = "1500"

[device "pci.8"]
  driver = "pcie-root-port"
  port = "18"
  chassis = "8"
  bus = "pcie.0"
  multifunction = "on"
  addr = "0x8"

[netdev "hostnet1"]
  type = "tap"
  ifname = "nbu2x1"
  br = "br2"
  script = "/etc/xen/scripts/qemu-ifup"
  downscript = "no"
  vhost = "on"

[device "net1"]
  driver = "virtio-net-pci"
  netdev = "hostnet1"
  mac = "02:16:3e:00:00:02"
  bus = "pci.8"
  addr = "0x0"
  host_mtu = "1500"

[device "pci.7"]
  driver = "pcie-root-port"
  port = "17"
  chassis = "7"
  bus = "pcie.0"
  multifunction = "on"
  addr = "0x7"

[device "pcie-bridge.7"]
  driver = "pcie-pci-bridge"
  bus = "pci.7"
  addr = "0x0"

[device]
  driver = "vfio-pci"
  host = "06:00.0"
  bus = "pcie-bridge.7"
  addr = "0x1"

[device "pci.9"]
  driver = "pcie-root-port"
  port = "19"
  chassis = "9"
  bus = "pcie.0"
  multifunction = "on"
  addr = "0x9"

[device]
  driver = "vfio-pci"
  host = "00:15.0"
  bus = "pci.9"
  addr = "0x0"

[device]
  driver = "vfio-pci"
  host = "06:00.2"
  bus = "pcie-bridge.7"
  addr = "0x3"

[device]
  driver = "vfio-pci"
  host = "06:00.1"
  bus = "pcie-bridge.7"
  addr = "0x2"

[device "pci.5"]
  driver = "pcie-root-port"
  port = "15"
  chassis = "5"
  bus = "pcie.0"
  multifunction = "on"
  addr = "0x5"

[device]
  driver = "vfio-pci"
  host = "08:00.0"
  bus = "pci.5"
  addr = "0x0"
`
	g.Expect(buffer.String()).To(Equal(expectedConfig))

	// Try re-ordering functions of a multifunction device. This should be allowed.
	pciAssignments[0].netIntfOrder = 3
	pciAssignments[3].netIntfOrder = 2
	err = addrAllocator.allocate()
	g.Expect(err).ToNot(HaveOccurred())

	g.Expect(virtualNetworks[0].pciDeviceID).To(Equal(6))
	g.Expect(virtualNetworks[1].pciDeviceID).To(Equal(8))
	g.Expect(pciAssignments[0].pciBridgeID).To(Equal(7))
	g.Expect(pciAssignments[0].pciDeviceID).To(Equal(2)) // 1 -> 2
	g.Expect(pciAssignments[1].pciBridgeID).To(Equal(0))
	g.Expect(pciAssignments[1].pciDeviceID).To(Equal(9))
	g.Expect(pciAssignments[2].pciBridgeID).To(Equal(7))
	g.Expect(pciAssignments[2].pciDeviceID).To(Equal(3))
	g.Expect(pciAssignments[3].pciBridgeID).To(Equal(7))
	g.Expect(pciAssignments[3].pciDeviceID).To(Equal(1)) // 2 -> 1
	g.Expect(pciAssignments[4].pciBridgeID).To(Equal(0))
	g.Expect(pciAssignments[4].pciDeviceID).To(Equal(5))

	// Try to put virtual interface in-between functions of a multifunction device.
	// This should not be allowed.
	virtualNetworks[1].VifOrder = 3
	pciAssignments[0].netIntfOrder = 4

	err = addrAllocator.allocate()
	g.Expect(err).To(HaveOccurred())
	g.Expect(err.Error()).To(ContainSubstring("Invalid VIF nbu2x1 configuration: " +
		"user-defined network interface order disrupts the function sequence " +
		"of the multifunction PCI device 0000:06:00"))
	// Revert the invalid config change.
	virtualNetworks[1].VifOrder = 4
	pciAssignments[0].netIntfOrder = 3
	err = addrAllocator.allocate()
	g.Expect(err).ToNot(HaveOccurred())

	// Try to put PCI-passthrough network device in-between functions of a multifunction
	// device. This should not be allowed.
	pciAssignments[4].netIntfOrder = 3
	pciAssignments[0].netIntfOrder = 4

	err = addrAllocator.allocate()
	g.Expect(err).To(HaveOccurred())
	fmt.Println(err.Error())
	g.Expect(err.Error()).To(ContainSubstring("User-defined network interface order " +
		"disrupts the function sequence of the multifunction PCI devices 0000:06:00 and 0000:08:00"))
}

func TestCreateDomConfigRngPciDefault(t *testing.T) {
	conf, err := os.CreateTemp("/tmp", "config")
	if err != nil {
		t.Fatalf("Can't create config file for a domain: %v", err)
	}
	defer os.Remove(conf.Name())

	diskConfigs, diskStatuses := qemuDisks()
	config, aa := domainConfigAndAssignableAdapters(diskConfigs)
	config.VirtualizationMode = types.HVM

	if err := kvmArm.CreateDomConfig(DefaultDomainName, config, types.DomainStatus{},
		diskStatuses, &aa, nil, swtpmCtrlSock, conf); err != nil {
		t.Fatalf("CreateDomConfig failed: %v", err)
	}

	result, err := os.ReadFile(conf.Name())
	if err != nil {
		t.Fatalf("reading conf file failed: %v", err)
	}
	content := string(result)

	if !strings.Contains(content, `driver = "virtio-rng-pci"`) {
		t.Errorf("expected virtio-rng-pci device in default ARM HVM config, got:\n%s", content)
	}
	if !strings.Contains(content, `filename = "/dev/urandom"`) {
		t.Errorf("expected backend filename /dev/urandom in config, got:\n%s", content)
	}
	if !strings.Contains(content, `max-bytes = "4096"`) || !strings.Contains(content, `period = "1000"`) {
		t.Errorf("expected max-bytes=4096 and period=1000 in config, got:\n%s", content)
	}
	if strings.Contains(content, `virtio-rng-device`) {
		t.Errorf("unexpected virtio-rng-device in default config")
	}

	// Verify RNG appears before eve-vsock0
	rngIdx := strings.Index(content, `driver = "virtio-rng-pci"`)
	vsockIdx := strings.Index(content, `driver = "vhost-vsock-pci"`)
	if rngIdx == -1 || vsockIdx == -1 || rngIdx >= vsockIdx {
		t.Errorf("virtio-rng-pci must appear immediately before eve-vsock0 (rngIdx: %d, vsockIdx: %d)", rngIdx, vsockIdx)
	}
}

func TestCreateDomConfigRngMmio(t *testing.T) {
	conf, err := os.CreateTemp("/tmp", "config")
	if err != nil {
		t.Fatalf("Can't create config file for a domain: %v", err)
	}
	defer os.Remove(conf.Name())

	diskConfigs, diskStatuses := qemuDisks()
	config, aa := domainConfigAndAssignableAdapters(diskConfigs)
	config.VirtualizationMode = types.HVM

	// Add an adapter requesting MMIO RNG transport
	config.IoAdapterList = append(config.IoAdapterList, types.IoAdapter{
		Type: types.IoOther,
		Name: "rng-mmio",
	})
	aa.IoBundleList = append(aa.IoBundleList, types.IoBundle{
		Type:            types.IoOther,
		AssignmentGroup: "rng-mmio",
		Phylabel:        "rng-mmio",
		Logicallabel:    "rng-mmio",
		UsedByUUID:      config.UUIDandVersion.UUID,
		Cbattr:          map[string]string{"rng": "mmio"},
	})

	if err := kvmArm.CreateDomConfig(DefaultDomainName, config, types.DomainStatus{},
		diskStatuses, &aa, nil, swtpmCtrlSock, conf); err != nil {
		t.Fatalf("CreateDomConfig failed: %v", err)
	}

	result, err := os.ReadFile(conf.Name())
	if err != nil {
		t.Fatalf("reading conf file failed: %v", err)
	}
	content := string(result)

	if !strings.Contains(content, `driver = "virtio-rng-device"`) {
		t.Errorf("expected virtio-rng-device in MMIO config, got:\n%s", content)
	}
	if !strings.Contains(content, `bus = "virtio-mmio-bus.0"`) {
		t.Errorf("expected bus = virtio-mmio-bus.0 in MMIO config, got:\n%s", content)
	}
	if strings.Contains(content, `virtio-rng-pci`) {
		t.Errorf("unexpected virtio-rng-pci in MMIO config")
	}
}

func TestCreateDomConfigRngOff(t *testing.T) {
	conf, err := os.CreateTemp("/tmp", "config")
	if err != nil {
		t.Fatalf("Can't create config file for a domain: %v", err)
	}
	defer os.Remove(conf.Name())

	diskConfigs, diskStatuses := qemuDisks()
	config, aa := domainConfigAndAssignableAdapters(diskConfigs)
	config.VirtualizationMode = types.HVM

	// Add an adapter explicitly disabling RNG
	config.IoAdapterList = append(config.IoAdapterList, types.IoAdapter{
		Type: types.IoOther,
		Name: "rng-off",
	})
	aa.IoBundleList = append(aa.IoBundleList, types.IoBundle{
		Type:            types.IoOther,
		AssignmentGroup: "rng-off",
		Phylabel:        "rng-off",
		Logicallabel:    "rng-off",
		UsedByUUID:      config.UUIDandVersion.UUID,
		Cbattr:          map[string]string{"rng": "off"},
	})

	if err := kvmArm.CreateDomConfig(DefaultDomainName, config, types.DomainStatus{},
		diskStatuses, &aa, nil, swtpmCtrlSock, conf); err != nil {
		t.Fatalf("CreateDomConfig failed: %v", err)
	}

	result, err := os.ReadFile(conf.Name())
	if err != nil {
		t.Fatalf("reading conf file failed: %v", err)
	}
	content := string(result)

	if strings.Contains(content, `virtio-rng-pci`) || strings.Contains(content, `virtio-rng-device`) {
		t.Errorf("unexpected RNG device in config when rng=off:\n%s", content)
	}
}

func TestCreateDomConfigRngOciContainerAndX86Exclusion(t *testing.T) {
	diskConfigs, diskStatuses := qemuDisks()

	// 1. OCI Container on ARM
	confOci, err := os.CreateTemp("/tmp", "config-oci")
	if err != nil {
		t.Fatalf("Can't create config file: %v", err)
	}
	defer os.Remove(confOci.Name())

	configOci, aaOci := domainConfigAndAssignableAdapters(diskConfigs)
	configOci.VirtualizationMode = types.NOHYPER
	configOci.DiskConfigList = []types.DiskConfig{{Format: zconfig.Format_CONTAINER}}

	if err := kvmArm.CreateDomConfig(DefaultDomainName, configOci, types.DomainStatus{},
		diskStatuses, &aaOci, nil, swtpmCtrlSock, confOci); err != nil {
		t.Fatalf("CreateDomConfig failed for OCI: %v", err)
	}
	resOci, _ := os.ReadFile(confOci.Name())
	if strings.Contains(string(resOci), `virtio-rng`) {
		t.Errorf("OCI container on ARM must not gain virtio-rng")
	}

	// 2. x86 machine (pc-q35)
	confX86, err := os.CreateTemp("/tmp", "config-x86")
	if err != nil {
		t.Fatalf("Can't create config file: %v", err)
	}
	defer os.Remove(confX86.Name())

	configX86, aaX86 := domainConfigAndAssignableAdapters(diskConfigs)
	configX86.VirtualizationMode = types.HVM

	if err := kvmIntel.CreateDomConfig(DefaultDomainName, configX86, types.DomainStatus{},
		diskStatuses, &aaX86, nil, swtpmCtrlSock, confX86); err != nil {
		t.Fatalf("CreateDomConfig failed for x86: %v", err)
	}
	resX86, _ := os.ReadFile(confX86.Name())
	if strings.Contains(string(resX86), `virtio-rng`) {
		t.Errorf("x86 machine must not gain virtio-rng")
	}
}

func TestCreateDomConfigRngBadBackendPath(t *testing.T) {
	conf, err := os.CreateTemp("/tmp", "config-good")
	if err != nil {
		t.Fatalf("Can't create config file: %v", err)
	}
	defer os.Remove(conf.Name())

	// Write initial good content
	initialContent := "initial valid config\n"
	if err := os.WriteFile(conf.Name(), []byte(initialContent), 0644); err != nil {
		t.Fatalf("writing initial config failed: %v", err)
	}

	// Point rngBackendPath at a regular file
	regularFile, err := os.CreateTemp("/tmp", "fake-urandom")
	if err != nil {
		t.Fatalf("creating regular file failed: %v", err)
	}
	defer os.Remove(regularFile.Name())

	origPath := rngBackendPath
	rngBackendPath = regularFile.Name()
	defer func() { rngBackendPath = origPath }()

	diskConfigs, diskStatuses := qemuDisks()
	config, aa := domainConfigAndAssignableAdapters(diskConfigs)
	config.VirtualizationMode = types.HVM

	err = kvmArm.CreateDomConfig(DefaultDomainName, config, types.DomainStatus{},
		diskStatuses, &aa, nil, swtpmCtrlSock, conf)
	if err == nil {
		t.Fatalf("expected CreateDomConfig to fail when backend path is a regular file")
	}

	// Confirm initial file was not overwritten
	savedContent, err := os.ReadFile(conf.Name())
	if err != nil {
		t.Fatalf("reading config file failed: %v", err)
	}
	if string(savedContent) != initialContent {
		t.Errorf("expected previous config file to be preserved on failure, got: %s", string(savedContent))
	}
}

func TestCreateDomConfigRngInvalidAndConflictingBundles(t *testing.T) {
	diskConfigs, diskStatuses := qemuDisks()

	// 1. Conflicting bundles (one says pci, one says mmio)
	conf, _ := os.CreateTemp("/tmp", "config-conflict")
	defer os.Remove(conf.Name())

	config, aa := domainConfigAndAssignableAdapters(diskConfigs)
	config.VirtualizationMode = types.HVM
	config.IoAdapterList = append(config.IoAdapterList,
		types.IoAdapter{Type: types.IoOther, Name: "rng1"},
		types.IoAdapter{Type: types.IoOther, Name: "rng2"},
	)
	aa.IoBundleList = append(aa.IoBundleList,
		types.IoBundle{
			Type:            types.IoOther,
			AssignmentGroup: "rng1",
			Phylabel:        "rng1",
			Logicallabel:    "rng1",
			UsedByUUID:      config.UUIDandVersion.UUID,
			Cbattr:          map[string]string{"rng": "pci"},
		},
		types.IoBundle{
			Type:            types.IoOther,
			AssignmentGroup: "rng2",
			Phylabel:        "rng2",
			Logicallabel:    "rng2",
			UsedByUUID:      config.UUIDandVersion.UUID,
			Cbattr:          map[string]string{"rng": "mmio"},
		},
	)

	err := kvmArm.CreateDomConfig(DefaultDomainName, config, types.DomainStatus{},
		diskStatuses, &aa, nil, swtpmCtrlSock, conf)
	if err == nil {
		t.Errorf("expected error on conflicting rng attributes, got nil")
	}

	// 2. Combining rng with shmsize
	conf2, _ := os.CreateTemp("/tmp", "config-shm-rng")
	defer os.Remove(conf2.Name())

	config2, aa2 := domainConfigAndAssignableAdapters(diskConfigs)
	config2.VirtualizationMode = types.HVM
	config2.IoAdapterList = append(config2.IoAdapterList, types.IoAdapter{Type: types.IoOther, Name: "bad-rng"})
	aa2.IoBundleList = append(aa2.IoBundleList, types.IoBundle{
		Type:            types.IoOther,
		AssignmentGroup: "bad-rng",
		Phylabel:        "bad-rng",
		Logicallabel:    "bad-rng",
		UsedByUUID:      config2.UUIDandVersion.UUID,
		Cbattr:          map[string]string{"rng": "mmio", "shmsize": "1M"},
	})

	err2 := kvmArm.CreateDomConfig(DefaultDomainName, config2, types.DomainStatus{},
		diskStatuses, &aa2, nil, swtpmCtrlSock, conf2)
	if err2 == nil {
		t.Errorf("expected error when combining rng with shmsize, got nil")
	}

	// 3. Unknown rng attribute value
	conf3, _ := os.CreateTemp("/tmp", "config-unknown-rng")
	defer os.Remove(conf3.Name())

	config3, aa3 := domainConfigAndAssignableAdapters(diskConfigs)
	config3.VirtualizationMode = types.HVM
	config3.IoAdapterList = append(config3.IoAdapterList, types.IoAdapter{Type: types.IoOther, Name: "unknown-rng"})
	aa3.IoBundleList = append(aa3.IoBundleList, types.IoBundle{
		Type:            types.IoOther,
		AssignmentGroup: "unknown-rng",
		Phylabel:        "unknown-rng",
		Logicallabel:    "unknown-rng",
		UsedByUUID:      config3.UUIDandVersion.UUID,
		Cbattr:          map[string]string{"rng": "invalid"},
	})

	err3 := kvmArm.CreateDomConfig(DefaultDomainName, config3, types.DomainStatus{},
		diskStatuses, &aa3, nil, swtpmCtrlSock, conf3)
	if err3 == nil {
		t.Errorf("expected error for unknown rng attribute 'invalid', got nil")
	}

	// 4. Combining rng with uart
	conf4, _ := os.CreateTemp("/tmp", "config-uart-rng")
	defer os.Remove(conf4.Name())

	config4, aa4 := domainConfigAndAssignableAdapters(diskConfigs)
	config4.VirtualizationMode = types.HVM
	config4.IoAdapterList = append(config4.IoAdapterList, types.IoAdapter{Type: types.IoOther, Name: "uart-rng"})
	aa4.IoBundleList = append(aa4.IoBundleList, types.IoBundle{
		Type:            types.IoOther,
		AssignmentGroup: "uart-rng",
		Phylabel:        "uart-rng",
		Logicallabel:    "uart-rng",
		UsedByUUID:      config4.UUIDandVersion.UUID,
		Cbattr:          map[string]string{"rng": "pci", "uart": "1"},
	})

	err4 := kvmArm.CreateDomConfig(DefaultDomainName, config4, types.DomainStatus{},
		diskStatuses, &aa4, nil, swtpmCtrlSock, conf4)
	if err4 == nil {
		t.Errorf("expected error when combining rng with uart, got nil")
	}
}
